-- G-NET system testbench (generated by sim/zn2/system/gen_tb.py from this
-- template; docs/zn2_layer_design.md 16): psx_top with ZN2_BOARD = 1 and
-- the LEAN trims, the real sdram.sv (R1 simulation copy) with a chip model
-- preloaded with the BIOS and flash images, a DDR3 model (VRAM, SPU RAM,
-- card image), the CAT702 keys and card metadata through the loader port.
-- gnet_fc runs in Verilator (sim/zn2/cosim). Logs (in LOGDIR):
--   gpu.log   every CPU write to GP0/GP1 (t, port, data), as oracle.lua's
--             gpu.log; zn.log every expansion bus request; sio.log every
--             SIO0 access; progress.log the CPU PC every 100 us.
-- Inputs are game-derived files (BIOS, flash, keys, card): run from
-- sim/zn2/work/ (gitignored).
-- SPLIT (set by gen_tb.py): 0 = upstream clocking, as on zn2-layer; 1 =
-- psx_top CPU_CLK_SPLIT with the CPU group (and zn2_board, the SDRAM and
-- its chip model) on 50.000 / 100.000 MHz, clk1x / clk2x started PHASE
-- later, zn2_board's flash port to SDRAM channel 3 through zn2_ch3_arb as in
-- PSX.sv (docs/r1_cpu_domain_design.md, "ZN-2 layer in the CPU group"); the
-- logs are then sampled on the CPU clock. SPLIT = 1 supports LOAD_MODE = 0
-- only (the downloads would cross through PSX.sv's channel 3 handshake,
-- which this bench does not model).

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use STD.textio.all;
use work.pJoypad.all;

entity sdram_chip_full is
   generic
   (
      BIOS_FILE  : string;
      U30_FILE   : string;
      FLASH_SKIP : integer := 0;      -- loader test: first bytes of U30_FILE not preloaded (A5A5h)
      READ_DQM   : boolean := true;   -- model read DQM (false: reads ignore DQM, the old model)
      BIOS_CHK   : string  := ""      -- loader test: file compared at 0x800000 on chk
   );
   port
   (
      chk   : in  boolean := false;   -- loader test: compare the downloaded ranges
      clk   : in  std_logic;
      ncs   : in  std_logic;
      nras  : in  std_logic;
      ncas  : in  std_logic;
      nwe   : in  std_logic;
      ba    : in  std_logic_vector(1 downto 0);
      a     : in  std_logic_vector(12 downto 0);
      dq_w  : in  std_logic_vector(15 downto 0);
      dq_r  : out std_logic_vector(15 downto 0)
   );
end entity;

-- 32 MB, word key = ba & row & column = byte address / 2 (sdram.sv maps
-- address bits 25:1 to bank, row, column in that order). Commands on the
-- falling controller clock edge, CAS latency 2, burst 2 (as tb_r1_mem.vhd).
-- DQML/DQMH are A11/A12 (sdram.sv 88). Writes: a byte is written only with
-- its DQM low (latency 0). Reads: DQM has a latency of 2 clocks (standard
-- SDR SDRAM behaviour, JEDEC SDR SDRAM; the MiSTer module's data sheet page is
-- needs-review: none is in the datasheet library), so the first word of
-- the burst is masked by DQM at the READ command and the second by DQM one
-- clock later; a masked byte is not driven by the chip and reads here as
-- E7h (on the board it is whatever the bus holds).
architecture sim of sdram_chip_full is
begin
   process (clk)
      type t_mem is array(0 to 2**24 - 1) of integer range 0 to 65535;
      type t_mem_ptr is access t_mem;
      variable mem  : t_mem_ptr := null;
      type t_rows is array(0 to 3) of unsigned(12 downto 0);
      variable rows : t_rows := (others => (others => '0'));
      type t_q is array(0 to 4) of std_logic_vector(15 downto 0);
      variable q    : t_q := (others => (others => 'Z'));
      variable key  : integer;
      variable bank : integer;
      variable d    : std_logic_vector(15 downto 0);
      type t_cf is file of character;
      file f        : t_cf;
      variable st   : file_open_status;
      variable c0, c1 : character;
      variable n    : integer;

      variable chk_1 : boolean := false;
      variable bad, good : integer;
      variable rd_pend : boolean := false;   -- second burst word waits for its DQM

      -- skip: bytes at the start of the file left as A5A5h (to be downloaded)
      procedure load(name : string; byte_addr : integer; skip : integer := 0) is
      begin
         file_open(st, f, name, read_mode);
         assert st = open_ok report "cannot open " & name severity failure;
         n := byte_addr / 2;
         while not endfile(f) loop
            read(f, c0);
            c1 := character'val(255);
            if not endfile(f) then read(f, c1); end if;
            if 2 * (n - byte_addr / 2) < skip then
               mem(n) := 16#A5A5#;
            else
               mem(n) := character'pos(c0) + 256 * character'pos(c1);
            end if;
            n := n + 1;
         end loop;
         file_close(f);
         report "loaded " & name & " at byte " & integer'image(byte_addr) & ", " & integer'image(2 * (n - byte_addr / 2)) &
                " bytes, first " & integer'image(skip) & " left to the download";
      end procedure;

      -- compare bytes [0, count) of a file with the memory at byte_addr
      procedure compare(name : string; byte_addr : integer; count : integer) is
      begin
         file_open(st, f, name, read_mode);
         assert st = open_ok report "cannot open " & name severity failure;
         n := byte_addr / 2; bad := 0; good := 0;
         while not endfile(f) and 2 * (n - byte_addr / 2) < count loop
            read(f, c0);
            c1 := character'val(255);
            if not endfile(f) then read(f, c1); end if;
            if mem(n) = character'pos(c0) + 256 * character'pos(c1) then
               good := good + 1;
            else
               if bad < 5 then
                  report "SDRAM check " & name & ": byte " & integer'image(2 * n) & " holds " &
                         integer'image(mem(n)) & ", file " & integer'image(character'pos(c0) + 256 * character'pos(c1));
               end if;
               bad := bad + 1;
            end if;
            n := n + 1;
         end loop;
         file_close(f);
         report "SDRAM check " & name & " at byte " & integer'image(byte_addr) & ": words equal " &
                integer'image(good) & ", different " & integer'image(bad);
      end procedure;
   begin
      if mem = null then
         mem := new t_mem'(others => 0);
         -- erased flash chips: U27 and the wave flashes (MAME intelfsh nvram_default)
         for i in 16#1200000# / 2 to 16#1A00000# / 2 - 1 loop mem(i) := 65535; end loop;
         for i in 16#1000000# / 2 to 16#1200000# / 2 - 1 loop mem(i) := 65535; end loop;
         if BIOS_FILE'length > 0 then
            load(BIOS_FILE, 16#800000#);
         end if;
         load(U30_FILE, 16#1000000#, FLASH_SKIP);
      end if;
      if chk and not chk_1 then
         if BIOS_CHK'length > 0 then
            compare(BIOS_CHK, 16#800000#, 16#80000#);
         end if;
         if FLASH_SKIP > 0 then
            compare(U30_FILE, 16#1000000#, FLASH_SKIP);
         end if;
      end if;
      chk_1 := chk;
      if falling_edge(clk) then
         for i in 0 to 3 loop q(i) := q(i + 1); end loop;
         q(4) := (others => 'Z');
         -- read DQM, latency 2: the burst's second word (now in q(2))
         if rd_pend and READ_DQM then
            if a(11) = '1' then q(2)(7 downto 0)  := x"E7"; end if;
            if a(12) = '1' then q(2)(15 downto 8) := x"E7"; end if;
            rd_pend := false;
         end if;
         if ncs = '0' then
            bank := to_integer(unsigned(ba));
            if nras = '0' and ncas = '1' and nwe = '1' then          -- ACTIVE
               rows(bank) := unsigned(a);
            elsif nras = '1' and ncas = '0' then
               key := to_integer(unsigned(ba) & rows(bank) & unsigned(a(8 downto 0)));
               if nwe = '1' then                                       -- READ, burst 2
                  q(2) := std_logic_vector(to_unsigned(mem(key), 16));
                  if READ_DQM and a(11) = '1' then q(2)(7 downto 0)  := x"E7"; end if;
                  if READ_DQM and a(12) = '1' then q(2)(15 downto 8) := x"E7"; end if;
                  key  := to_integer(to_unsigned(key, 24) xor x"000001");
                  q(3) := std_logic_vector(to_unsigned(mem(key), 16));
                  rd_pend := true;
               else                                                    -- WRITE, DQML = A11, DQMH = A12
                  d := std_logic_vector(to_unsigned(mem(key), 16));
                  if a(11) = '0' then d(7 downto 0)  := dq_w(7 downto 0);  end if;
                  if a(12) = '0' then d(15 downto 8) := dq_w(15 downto 8); end if;
                  mem(key) := to_integer(unsigned(d));
               end if;
            end if;
         end if;
         dq_r <= q(0);
      end if;
   end process;
end architecture;

------------------------------------------------------------------------------
-- DDR3 (Avalon, as sim/system/src/tb/ddrram_model.vhd): byte address
-- ADDR(27:3) = 64-bit word; reads answer BURSTCNT words after LAT cycles;
-- single-beat writes with byte enables. Low 16 MB (VRAM, SPU RAM, frame
-- buffers) and the card area (64 MB, 40,960,000 bytes) are stored.
------------------------------------------------------------------------------
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ddr3_model is
   generic
   (
      LAT       : integer := 15;
      CARD_FILE : string  := "";
      CARD_SKIP : integer := 0;       -- loader test: first bytes not preloaded (A5h), downloaded
      DUMPDIR   : string  := "."
   );
   port
   (
      chk        : in  boolean := false;   -- loader test: compare the downloaded card bytes
      clk        : in  std_logic;
      busy       : out std_logic := '0';
      burstcnt   : in  std_logic_vector(7 downto 0);
      addr       : in  std_logic_vector(27 downto 0);
      dout       : out std_logic_vector(63 downto 0) := (others => '0');
      dout_ready : out std_logic := '0';
      rd         : in  std_logic;
      din        : in  std_logic_vector(63 downto 0);
      be         : in  std_logic_vector(7 downto 0);
      we         : in  std_logic;
      dump_req   : in  integer := -1     -- a new value dumps VRAM (first 2 MB) to vram_<value>.bin
   );
end entity;

architecture sim of ddr3_model is
begin
   process
      constant NLOW  : integer := 2**21;                -- 16 MB
      constant CBASE : integer := 16#4000000# / 8;      -- card
      constant NCARD : integer := 40960000 / 8;
      type t_arr is array(natural range <>) of integer;
      type t_arr_ptr is access t_arr;
      variable lo_l, lo_h, ca_l, ca_h : t_arr_ptr;
      variable w, bc : integer;
      variable v     : std_logic_vector(63 downto 0);
      type t_cf is file of character;
      file f         : t_cf;
      variable st    : file_open_status;
      variable c     : character;
      variable n, k  : integer;
      variable last_dump : integer := -1;
      variable chk_1     : boolean := false;
      file fd        : t_cf;

      impure function get(word : integer) return std_logic_vector is
      begin
         if word < NLOW then
            return std_logic_vector(to_signed(lo_h(word), 32)) & std_logic_vector(to_signed(lo_l(word), 32));
         elsif word >= CBASE and word < CBASE + NCARD then
            return std_logic_vector(to_signed(ca_h(word - CBASE), 32)) & std_logic_vector(to_signed(ca_l(word - CBASE), 32));
         end if;
         return x"0000000000000000";
      end function;

      procedure put(word : integer; d : std_logic_vector(63 downto 0)) is
      begin
         if word < NLOW then
            lo_l(word) := to_integer(signed(d(31 downto 0))); lo_h(word) := to_integer(signed(d(63 downto 32)));
         elsif word >= CBASE and word < CBASE + NCARD then
            ca_l(word - CBASE) := to_integer(signed(d(31 downto 0))); ca_h(word - CBASE) := to_integer(signed(d(63 downto 32)));
         end if;
      end procedure;
   begin
      lo_l := new t_arr'(0 to NLOW - 1 => 0);
      lo_h := new t_arr'(0 to NLOW - 1 => 0);
      ca_l := new t_arr'(0 to NCARD - 1 => 0);
      ca_h := new t_arr'(0 to NCARD - 1 => 0);
      if CARD_FILE'length > 0 then
         file_open(st, f, CARD_FILE, read_mode);
         assert st = open_ok report "cannot open " & CARD_FILE severity failure;
         n := 0;
         while not endfile(f) and n < NCARD loop
            v := (others => '0');
            for b in 0 to 7 loop
               read(f, c);
               v(8 * b + 7 downto 8 * b) := std_logic_vector(to_unsigned(character'pos(c), 8));
            end loop;
            if 8 * n < CARD_SKIP then
               v := x"A5A5A5A5A5A5A5A5";
            end if;
            put(CBASE + n, v);
            n := n + 1;
         end loop;
         file_close(f);
         report "card image loaded: " & integer'image(8 * n) & " bytes, first " & integer'image(CARD_SKIP) & " left to the download";
      end if;
      loop
         wait until rising_edge(clk);
         if chk and not chk_1 and CARD_SKIP > 0 then
            file_open(st, f, CARD_FILE, read_mode);
            n := 0; k := 0;
            while 8 * n < CARD_SKIP loop
               for b in 0 to 7 loop
                  read(f, c);
                  v(8 * b + 7 downto 8 * b) := std_logic_vector(to_unsigned(character'pos(c), 8));
               end loop;
               if get(CBASE + n) /= v then
                  if k < 5 then
                     report "DDR3 card check: line at card byte " & integer'image(8 * n) & " holds " &
                            to_hstring(get(CBASE + n)) & ", image " & to_hstring(v);
                  end if;
                  k := k + 1;
               end if;
               n := n + 1;
            end loop;
            file_close(f);
            report "DDR3 card check: 8-byte lines equal " & integer'image(n - k) & ", different " & integer'image(k);
         end if;
         chk_1 := chk;
         if dump_req /= last_dump and dump_req >= 0 then
            last_dump := dump_req;
            file_open(st, fd, DUMPDIR & "/vram_" & integer'image(dump_req) & ".bin", write_mode);
            for i in 0 to 2**18 - 1 loop     -- 2 MB = 256 K words of 8 bytes
               v := get(i);
               for b in 0 to 7 loop
                  write(fd, character'val(to_integer(unsigned(v(8 * b + 7 downto 8 * b)))));
               end loop;
            end loop;
            file_close(fd);
         end if;
         if rd = '1' then
            w  := to_integer(unsigned(addr(27 downto 3)));
            bc := to_integer(unsigned(burstcnt));
            wait until rising_edge(clk);
            for i in 1 to LAT loop wait until rising_edge(clk); end loop;
            for i in 0 to bc - 1 loop
               dout       <= get(w + i);
               dout_ready <= '1';
               wait until rising_edge(clk);
            end loop;
            dout_ready <= '0';
         elsif we = '1' then
            w := to_integer(unsigned(addr(27 downto 3)));
            v := get(w);
            for b in 0 to 7 loop
               if be(b) = '1' then v(8 * b + 7 downto 8 * b) := din(8 * b + 7 downto 8 * b); end if;
            end loop;
            put(w, v);
         end if;
      end loop;
   end process;
end architecture;

------------------------------------------------------------------------------
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use STD.textio.all;
use work.pJoypad.all;

entity tb_zn2_system is
   generic
   (
      BIOS_FILE : string  := "bios.bin";
      U30_FILE  : string  := "u30.bin";
      KEY_FILE  : string  := "keys.hex";       -- 16 lines: TT10 then TT16
      META_FILE : string  := "";               -- 1024 lines (IDNT, CIS, KEY), "" = no card
      CARD_FILE : string  := "";
      LOGDIR    : string  := ".";
      RUN_MS    : integer := 200;
      DUMP_MS   : integer := 250;      -- VRAM dump at the first vsync after every DUMP_MS
      READ_DQM  : boolean := true;     -- SDRAM model applies read DQM (sdram_chip_full)
      -- LOAD_MODE = 1: the MRA's downloads go through a model of hps_io and of
      -- PSX.sv's G-NET loader logic (PSX.sv 532-556, 572-592, 660-683,
      -- 1003-1006, 1488-1495) instead of preloading: index 0 BIOS_FILE,
      -- 2 KEYS_BIN, 3 the first FLASH_SKIP bytes of U30_FILE, 4 META_BIN,
      -- 5 the first CARD_SKIP bytes of CARD_FILE; the rest of U30_FILE and
      -- CARD_FILE is preloaded. RUN_MS counts from the end of the downloads.
      LOAD_MODE  : integer := 0;
      KEYS_BIN   : string  := "keys.bin";
      META_BIN   : string  := "meta.bin";
      FLASH_SKIP : integer := 0;
      CARD_SKIP  : integer := 0;
      PRE_RUN_US : integer := 500;     -- core running before the first download
      GAP_US     : integer := 2000;    -- between two downloads
      PHASE      : time    := 7 ns;    -- SPLIT = 1: PS1 clocks start this much later
      CPU_PHASE  : time    := 0 ns;    -- SPLIT = 1: CPU clocks start this much later
      EARLY_READY : integer := 0;      -- SPLIT = 1: sdram.sv EARLY_READY (option B)
      READ_OVERLAP : integer := 0;     -- psx_top ZN2_READ_OVERLAP (memorymux read overlap)
                                       -- (sweep.sh varies both; the full-system harness: PHASE 0,
                                       -- CPU clocks first edge at 5 ns)
      -- trace.log: for TRACE_US after every znsecsel write of 84h (a TT16
      -- session), every new CPU PC outside the SIO0 poll loop (2A10-2A6F)
      -- and every RAM write (address, data, byte enables); 0 = off
      TRACE_US   : integer := 0
   );
end entity;

architecture sim of tb_zn2_system is

   constant SPLIT : integer := @SPLIT@;

   function sel_str(c : boolean; a, b : string) return string is
   begin
      if c then return a; else return b; end if;
   end function;

   function b2sl(c : boolean) return std_logic is
   begin
      if c then return '1'; else return '0'; end if;
   end function;

   component sdram is
      generic (CLK_FAST_RATIO : integer := 3; EARLY_READY : integer := 0);
      port (
         init, clk, clk_base, SDRAM_EN : in std_logic;
         SDRAM_DQ    : out std_logic_vector(15 downto 0);
         SDRAM_DQ_IN : in  std_logic_vector(15 downto 0);
         idx_o       : out std_logic;
         SDRAM_A     : out std_logic_vector(12 downto 0);
         SDRAM_DQML, SDRAM_DQMH : out std_logic;
         SDRAM_BA    : out std_logic_vector(1 downto 0);
         SDRAM_nCS, SDRAM_nWE, SDRAM_nRAS, SDRAM_nCAS, SDRAM_CKE, SDRAM_CLK : out std_logic;
         refreshForce : in std_logic;
         ram_idle     : out std_logic;
         ch1_addr : in std_logic_vector(26 downto 0);
         ch1_dout : out std_logic_vector(127 downto 0);
         ch1_dout32 : out std_logic_vector(31 downto 0);
         ch1_din  : in std_logic_vector(15 downto 0);
         ch1_req, ch1_rnw, ch1_dma : in std_logic;
         ch1_cntDMA : in std_logic_vector(1 downto 0);
         ch1_cache : in std_logic;
         ch1_ready : out std_logic;
         cache_wr : out std_logic_vector(3 downto 0);
         cache_data : out std_logic_vector(31 downto 0);
         cache_addr : out std_logic_vector(7 downto 0);
         dma_wr, dma_reqprocessed : out std_logic;
         dma_data : out std_logic_vector(31 downto 0);
         ch2_addr : in std_logic_vector(26 downto 0);
         ch2_dout : out std_logic_vector(31 downto 0);
         ch2_din  : in std_logic_vector(31 downto 0);
         ch2_req, ch2_rnw : in std_logic;
         ch2_be : in std_logic_vector(3 downto 0);
         ch2_ready : out std_logic;
         ch3_addr : in std_logic_vector(26 downto 0);
         ch3_dout : out std_logic_vector(31 downto 0);
         ch3_din  : in std_logic_vector(31 downto 0);
         ch3_req, ch3_rnw : in std_logic;
         ch3_be : in std_logic_vector(3 downto 0);
         ch3_ready : out std_logic;
         dmafifo_adr  : in std_logic_vector(26 downto 0);
         dmafifo_data : in std_logic_vector(31 downto 0);
         dmafifo_empty : in std_logic;
         dmafifo_read : out std_logic
      );
   end component;

   constant JOY0 : joypad_t := ('0','0','0','0','0','0','0','0','0','0','0','0',
                                '0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0',
                                -- analog -1: psx_top adds 128 for the gun coordinates (8-bit signed)
                                (others => '1'), (others => '1'), (others => '1'), (others => '1'));

   constant H : time := 2461 ps;   -- half period of the 203.2 MHz base: clk3x 4H, clk2x 6H, clk1x 12H

   signal clk1x, clk2x, clk3x : std_logic := '1';
   signal clkvid              : std_logic := '0';
   signal f_clk, f_clk2       : std_logic := '1';   -- CPU PLL (SPLIT = 1): 50 and 100 MHz, rising edges aligned
   signal fl_ready            : std_logic;          -- SPLIT = 1: flash port ready from zn2_ch3_arb
   signal reset               : std_logic;
   signal sdram_init          : std_logic;
   -- one driver each (a second process driving reset or sdram_init, even
   -- under a false condition, would resolve them to X)
   signal reset_pre, reset_ld : std_logic := '1';    -- preload startup / PSX.sv reset register
   signal init_pre, init_ld   : std_logic := '1';
   signal done_sim            : boolean := false;

   signal ram_refresh, ram_rnw, ram_ena, ram_dma, ram_cache : std_logic;
   signal ram_dataWrite       : std_logic_vector(31 downto 0);
   signal ram_Adr             : std_logic_vector(24 downto 0);
   signal ram_cntDMA          : std_logic_vector(1 downto 0);
   signal ram_be              : std_logic_vector(3 downto 0);
   signal ram_done            : std_logic;
   signal ch1_ready, ch2_ready : std_logic;
   signal ch1_dout32          : std_logic_vector(31 downto 0);
   signal dmafifo_adr         : std_logic_vector(22 downto 0);
   signal dmafifo_data        : std_logic_vector(31 downto 0);
   signal dmafifo_empty       : std_logic;
   signal dmafifo_read        : std_logic;
   signal cache_wr            : std_logic_vector(3 downto 0);
   signal cache_data          : std_logic_vector(31 downto 0);
   signal cache_addr          : std_logic_vector(7 downto 0);
   signal dma_wr, dma_reqprocessed : std_logic;
   signal dma_data            : std_logic_vector(31 downto 0);
   signal ch3_req, ch3_rnw, ch3_ready : std_logic;
   signal ch3_addr            : std_logic_vector(26 downto 0);
   signal ch3_din, ch3_dout   : std_logic_vector(31 downto 0);
   signal ch3_be              : std_logic_vector(3 downto 0);
   signal sd_dq_w, sd_dq_r    : std_logic_vector(15 downto 0);
   signal sd_a                : std_logic_vector(12 downto 0);
   signal sd_ba               : std_logic_vector(1 downto 0);
   signal sd_ncs, sd_nwe, sd_nras, sd_ncas : std_logic;

   signal ddr3_BUSY, ddr3_DOUT_READY, ddr3_WE, ddr3_RD : std_logic;
   signal ddr3_DOUT, ddr3_DIN : std_logic_vector(63 downto 0);
   signal ddr3_BURSTCNT       : std_logic_vector(7 downto 0);
   signal ddr3_ADDR           : std_logic_vector(27 downto 0);
   signal ddr3_BE             : std_logic_vector(7 downto 0);

   signal card_present        : std_logic := '0';
   signal card_present_m      : std_logic;
   signal ld_wr_m             : std_logic;
   signal ld_target_m         : std_logic_vector(1 downto 0);
   signal ld_addr_m           : unsigned(10 downto 0);
   signal ld_data_m           : std_logic_vector(15 downto 0);
   signal card_dl_wr          : std_logic := '0';
   signal card_dl_addr        : unsigned(25 downto 0) := (others => '0');
   signal card_dl_data        : std_logic_vector(15 downto 0) := (others => '0');
   signal card_dl_busy        : std_logic;
   signal fl_req, fl_rnw      : std_logic;
   signal fl_addr             : std_logic_vector(26 downto 0);
   signal fl_din              : std_logic_vector(31 downto 0);
   signal fl_be               : std_logic_vector(3 downto 0);
   signal tb_reset            : std_logic := '1';   -- HPS reset (RESET in PSX.sv)
   signal chk                 : boolean := false;
   signal loads_done          : boolean := false;
   -- hps_io outputs (model)
   signal ioctl_download      : std_logic := '0';
   signal ioctl_index         : std_logic_vector(7 downto 0) := (others => '0');
   signal ioctl_wr            : std_logic := '0';
   signal ioctl_addr          : unsigned(26 downto 0) := (others => '0');
   signal ioctl_dout          : std_logic_vector(15 downto 0) := (others => '0');
   -- PSX.sv loader registers
   signal ioctl_wait          : std_logic := '0';
   signal bios_download, flash_download, keys_download, meta_download, card_download, ee_download : std_logic := '0';
   signal gnet_download       : std_logic;
   signal zn_ld_wr            : std_logic := '0';
   signal zn_ld_target        : std_logic_vector(1 downto 0) := "00";
   signal zn_ld_addr          : unsigned(10 downto 0) := (others => '0');
   signal zn_ld_data          : std_logic_vector(15 downto 0) := (others => '0');
   signal zn_card_loaded      : std_logic := '0';
   signal zn_card_wait        : std_logic := '0';
   signal ramdownload_wraddr  : std_logic_vector(26 downto 0) := (others => '0');
   signal ramdownload_wrdata  : std_logic_vector(31 downto 0) := (others => '0');
   signal ramdownload_wr      : std_logic := '0';
   signal dl_sel              : std_logic;
   signal zn_wd_hold          : unsigned(7 downto 0) := (others => '0');
   signal ld_wr               : std_logic := '0';
   signal ld_target           : std_logic_vector(1 downto 0) := "00";
   signal ld_addr             : unsigned(10 downto 0) := (others => '0');
   signal ld_data             : std_logic_vector(15 downto 0) := (others => '0');
   signal wd_reset            : std_logic;
   signal coin                : std_logic_vector(7 downto 0);
   signal vsync               : std_logic;
   signal dump_req            : integer := -1;
   signal frames              : integer := 0;

begin

   -- clocks: one base, rising edges of clk1x, clk2x and clk3x aligned
   process
      variable k : integer := 0;
   begin
      if SPLIT = 1 and k = 0 then wait for PHASE; end if;
      wait for H;
      k := k + 1;
      if k mod 2 = 0 then clk3x <= not clk3x; end if;
      if k mod 3 = 0 then clk2x <= not clk2x; end if;
      if k mod 6 = 0 then clk1x <= not clk1x; end if;
      if done_sim then wait; end if;
   end process;
   clkvid <= not clkvid after 9312 ps when not done_sim;   -- 53.69 MHz

   -- CPU PLL clocks, both from one process so their edges fall in the same delta
   gcpuclk : if SPLIT = 1 generate
      process
         variable k : integer := 0;
      begin
         if k = 0 then wait for CPU_PHASE; end if;
         wait for 5 ns;
         k := k + 1;
         f_clk2 <= not f_clk2;
         if k mod 2 = 0 then f_clk <= not f_clk; end if;
         if done_sim then wait; end if;
      end process;
      assert LOAD_MODE = 0 report "tb_zn2_system: SPLIT = 1 supports LOAD_MODE = 0 only" severity failure;
   end generate;

   dut : entity work.psx_top
   generic map
   (
      HAS_CD => 0, HAS_PADS => 0, HAS_SAVESTATES => 0, HAS_CHEATS => 0, HAS_MDEC => 0,
      VRAM_Y_BITS => 10, ZN2_BOARD => 1, ZN2_READ_OVERLAP => READ_OVERLAP,
      @SPLITGEN@
   )
   port map
   (
@PORTMAP@
   );

   -- PSX.sv 1291, 1314-1337
   ram_done <= ch1_ready or ch2_ready;

   -- the SDRAM controller and its chip on clk3x / clk1x (3:1), or with the
   -- CPU group on clk_cpu2x / clk_cpu (2:1)
   gsd0 : if SPLIT = 0 generate
   isdram : sdram
   generic map (CLK_FAST_RATIO => 3)
   port map (
      init => sdram_init, clk => clk3x, clk_base => clk1x, SDRAM_EN => '1',
      SDRAM_DQ => sd_dq_w, SDRAM_DQ_IN => sd_dq_r, idx_o => open,
      SDRAM_A => sd_a, SDRAM_DQML => open, SDRAM_DQMH => open, SDRAM_BA => sd_ba,
      SDRAM_nCS => sd_ncs, SDRAM_nWE => sd_nwe, SDRAM_nRAS => sd_nras, SDRAM_nCAS => sd_ncas,
      SDRAM_CKE => open, SDRAM_CLK => open,
      refreshForce => ram_refresh, ram_idle => open,
      ch1_addr => "00" & ram_Adr, ch1_dout => open, ch1_dout32 => ch1_dout32, ch1_din => (others => '0'),
      ch1_req => ram_ena and ram_rnw, ch1_rnw => '1', ch1_dma => ram_dma, ch1_cntDMA => ram_cntDMA,
      ch1_cache => ram_cache, ch1_ready => ch1_ready,
      cache_wr => cache_wr, cache_data => cache_data, cache_addr => cache_addr,
      dma_wr => dma_wr, dma_reqprocessed => dma_reqprocessed, dma_data => dma_data,
      ch2_addr => "00" & ram_Adr, ch2_dout => open, ch2_din => ram_dataWrite,
      ch2_req => ram_ena and not ram_rnw, ch2_rnw => '0', ch2_be => ram_be, ch2_ready => ch2_ready,
      ch3_addr => ch3_addr, ch3_dout => ch3_dout, ch3_din => ch3_din, ch3_req => ch3_req, ch3_rnw => ch3_rnw,
      ch3_be => ch3_be, ch3_ready => ch3_ready,
      dmafifo_adr => "0000" & dmafifo_adr, dmafifo_data => dmafifo_data, dmafifo_empty => dmafifo_empty,
      dmafifo_read => dmafifo_read
   );

   ichip : entity work.sdram_chip_full
   generic map (BIOS_FILE => sel_str(LOAD_MODE = 1, "", BIOS_FILE), U30_FILE => U30_FILE,
                FLASH_SKIP => FLASH_SKIP, BIOS_CHK => sel_str(LOAD_MODE = 1, BIOS_FILE, ""), READ_DQM => READ_DQM)
   port map (chk => chk, clk => clk3x, ncs => sd_ncs, nras => sd_nras, ncas => sd_ncas, nwe => sd_nwe,
             ba => sd_ba, a => sd_a, dq_w => sd_dq_w, dq_r => sd_dq_r);
   end generate;

   gsd1 : if SPLIT = 1 generate
   isdram : sdram
   generic map (CLK_FAST_RATIO => 2, EARLY_READY => EARLY_READY)
   port map (
      init => sdram_init, clk => f_clk2, clk_base => f_clk, SDRAM_EN => '1',
      SDRAM_DQ => sd_dq_w, SDRAM_DQ_IN => sd_dq_r, idx_o => open,
      SDRAM_A => sd_a, SDRAM_DQML => open, SDRAM_DQMH => open, SDRAM_BA => sd_ba,
      SDRAM_nCS => sd_ncs, SDRAM_nWE => sd_nwe, SDRAM_nRAS => sd_nras, SDRAM_nCAS => sd_ncas,
      SDRAM_CKE => open, SDRAM_CLK => open,
      refreshForce => ram_refresh, ram_idle => open,
      ch1_addr => "00" & ram_Adr, ch1_dout => open, ch1_dout32 => ch1_dout32, ch1_din => (others => '0'),
      ch1_req => ram_ena and ram_rnw, ch1_rnw => '1', ch1_dma => ram_dma, ch1_cntDMA => ram_cntDMA,
      ch1_cache => ram_cache, ch1_ready => ch1_ready,
      cache_wr => cache_wr, cache_data => cache_data, cache_addr => cache_addr,
      dma_wr => dma_wr, dma_reqprocessed => dma_reqprocessed, dma_data => dma_data,
      ch2_addr => "00" & ram_Adr, ch2_dout => open, ch2_din => ram_dataWrite,
      ch2_req => ram_ena and not ram_rnw, ch2_rnw => '0', ch2_be => ram_be, ch2_ready => ch2_ready,
      ch3_addr => ch3_addr, ch3_dout => ch3_dout, ch3_din => ch3_din, ch3_req => ch3_req, ch3_rnw => ch3_rnw,
      ch3_be => ch3_be, ch3_ready => ch3_ready,
      dmafifo_adr => "0000" & dmafifo_adr, dmafifo_data => dmafifo_data, dmafifo_empty => dmafifo_empty,
      dmafifo_read => dmafifo_read
   );

   ichip : entity work.sdram_chip_full
   generic map (BIOS_FILE => sel_str(LOAD_MODE = 1, "", BIOS_FILE), U30_FILE => U30_FILE,
                FLASH_SKIP => FLASH_SKIP, BIOS_CHK => sel_str(LOAD_MODE = 1, BIOS_FILE, ""), READ_DQM => READ_DQM)
   port map (chk => chk, clk => f_clk2, ncs => sd_ncs, nras => sd_nras, ncas => sd_ncas, nwe => sd_nwe,
             ba => sd_ba, a => sd_a, dq_w => sd_dq_w, dq_r => sd_dq_r);

   -- PSX.sv (GNET_ZN2 with GNET_CPU50): channel 3 shared between the
   -- download handshake (idle here: SPLIT = 1 preloads the SDRAM) and the
   -- flash port
   iarb : entity work.zn2_ch3_arb
   port map (
      clk => f_clk,
      a_req => '0', a_addr => (others => '0'), a_din => (others => '0'), a_rnw => '1', a_be => "0000", a_ready => open,
      b_req => fl_req, b_addr => fl_addr, b_din => fl_din, b_rnw => fl_rnw, b_be => fl_be, b_ready => fl_ready,
      ch3_req => ch3_req, ch3_addr => ch3_addr, ch3_din => ch3_din, ch3_rnw => ch3_rnw, ch3_be => ch3_be,
      ch3_ready => ch3_ready);
   end generate;

   iddr3 : entity work.ddr3_model
   generic map (LAT => 15, CARD_FILE => CARD_FILE, CARD_SKIP => CARD_SKIP, DUMPDIR => LOGDIR)
   port map (chk => chk, clk => clk2x, busy => ddr3_BUSY, burstcnt => ddr3_BURSTCNT, addr => ddr3_ADDR,
             dout => ddr3_DOUT, dout_ready => ddr3_DOUT_READY, rd => ddr3_RD, din => ddr3_DIN,
             be => ddr3_BE, we => ddr3_WE, dump_req => dump_req);

   -- ------------------------------------------------- PSX.sv loader logic
   -- preload mode: the startup process drives the loader port and reset;
   -- LOAD_MODE = 1: PSX.sv's logic (line references in the generic comment)
   -- between the hps_io model and psx_top
   card_present_m <= card_present when LOAD_MODE = 0 else zn_card_loaded;
   ld_wr_m        <= ld_wr        when LOAD_MODE = 0 else zn_ld_wr;
   ld_target_m    <= ld_target    when LOAD_MODE = 0 else zn_ld_target;
   ld_addr_m      <= ld_addr      when LOAD_MODE = 0 else zn_ld_addr;
   ld_data_m      <= ld_data      when LOAD_MODE = 0 else zn_ld_data;

   gnet_download <= flash_download or keys_download or meta_download or card_download or ee_download;
   reset         <= reset_pre when LOAD_MODE = 0 else reset_ld;
   sdram_init    <= init_pre  when LOAD_MODE = 0 else init_ld;

   process (clk1x)
   begin
      if rising_edge(clk1x) then
         -- PSX.sv 532, 549-554
         bios_download  <= ioctl_download and b2sl(ioctl_index(5 downto 0) = "000000");
         flash_download <= ioctl_download and b2sl(ioctl_index = x"03");
         keys_download  <= ioctl_download and b2sl(ioctl_index = x"02");
         meta_download  <= ioctl_download and b2sl(ioctl_index = x"04");
         card_download  <= ioctl_download and b2sl(ioctl_index = x"05");
         ee_download    <= ioctl_download and b2sl(ioctl_index = x"06");

         -- PSX.sv 209-213 (watchdog hold, status[100] = 0)
         if wd_reset = '1' then zn_wd_hold <= x"FF";
         elsif zn_wd_hold /= 0 then zn_wd_hold <= zn_wd_hold - 1; end if;

         -- PSX.sv 214, 1003-1006: reset register
         if LOAD_MODE = 1 then
            reset_ld <= tb_reset or bios_download or gnet_download or b2sl(zn_wd_hold /= 0);
         end if;

         -- PSX.sv 573-592
         zn_ld_wr   <= '0';
         card_dl_wr <= '0';
         if ioctl_wr = '1' then
            if (keys_download or meta_download or ee_download) = '1' then
               zn_ld_wr <= '1';
               if keys_download = '1' then zn_ld_target <= "00";
               elsif meta_download = '1' then zn_ld_target <= "01";
               else zn_ld_target <= "10"; end if;
               zn_ld_addr <= ioctl_addr(10 downto 0);
               zn_ld_data <= ioctl_dout;
            end if;
            if meta_download = '1' then zn_card_loaded <= '1'; end if;
            if card_download = '1' then
               card_dl_wr   <= '1';
               card_dl_addr <= ioctl_addr(25 downto 0);
               card_dl_data <= ioctl_dout;
            end if;
         end if;
         zn_card_wait <= card_dl_wr or card_dl_busy;

         -- PSX.sv 659-683 (exe and cdinfo downloads not used here)
         ramdownload_wr <= '0';
         if (bios_download or flash_download) = '1' then
            if ioctl_wr = '1' then
               if ioctl_addr(1) = '0' then
                  ramdownload_wrdata(15 downto 0) <= ioctl_dout;
                  if flash_download = '1' then
                     ramdownload_wraddr <= std_logic_vector(to_unsigned(16#1000000#, 27) + resize(ioctl_addr(23 downto 0), 27));
                  else
                     ramdownload_wraddr <= "0001" & "00" & ioctl_index(7 downto 6) & std_logic_vector(ioctl_addr(18 downto 0));
                  end if;
               else
                  ramdownload_wrdata(31 downto 16) <= ioctl_dout;
                  ramdownload_wr <= '1';
                  ioctl_wait     <= '1';
               end if;
            end if;
            if ch3_ready = '1' then ioctl_wait <= '0'; end if;
         elsif card_download = '1' then
            ioctl_wait <= zn_card_wait;
         else
            ioctl_wait <= '0';
         end if;
      end if;
   end process;

   -- PSX.sv 1488-1495: SDRAM ch3 to the downloads, else to the flash port
   dl_sel   <= bios_download or flash_download;
   gch3mux : if SPLIT = 0 generate
   ch3_addr <= ramdownload_wraddr when dl_sel = '1' else fl_addr;
   ch3_din  <= ramdownload_wrdata when dl_sel = '1' else fl_din;
   ch3_req  <= ramdownload_wr     when dl_sel = '1' else fl_req;
   ch3_rnw  <= '0'                when dl_sel = '1' else fl_rnw;
   ch3_be   <= "1111"             when dl_sel = '1' else fl_be;
   end generate;

   -- hps_io model (LOAD_MODE = 1): one 16-bit word per ioctl_wr, address
   -- from 0 in steps of 2 (hps_io.sv 671-694); the next word waits for
   -- ioctl_wait low (sys_top.v 256-262: io_ack is held while io_wait), and
   -- words are at least 10 clk1x cycles apart (HPS bridge accesses)
   gload : if LOAD_MODE = 1 generate
      process
         type t_cf is file of character;
         file f          : t_cf;
         variable st     : file_open_status;
         variable c0, c1 : character;
         variable a      : integer;

         procedure send(idx : integer; name : string; limit : integer) is
         begin
            file_open(st, f, name, read_mode);
            assert st = open_ok report "cannot open " & name severity failure;
            wait until rising_edge(clk1x);
            ioctl_index    <= std_logic_vector(to_unsigned(idx, 8));
            wait until rising_edge(clk1x);
            ioctl_download <= '1';
            for i in 1 to 20 loop wait until rising_edge(clk1x); end loop;
            a := 0;
            while not endfile(f) and (limit < 0 or a < limit) loop
               read(f, c0);
               c1 := character'val(0);
               if not endfile(f) then read(f, c1); end if;
               ioctl_addr <= to_unsigned(a, 27);
               ioctl_dout <= std_logic_vector(to_unsigned(character'pos(c1), 8)) & std_logic_vector(to_unsigned(character'pos(c0), 8));
               ioctl_wr   <= '1';
               wait until rising_edge(clk1x);
               ioctl_wr   <= '0';
               for i in 1 to 6 loop wait until rising_edge(clk1x); end loop;
               while ioctl_wait = '1' loop wait until rising_edge(clk1x); end loop;
               for i in 1 to 3 loop wait until rising_edge(clk1x); end loop;
               a := a + 2;
            end loop;
            file_close(f);
            for i in 1 to 20 loop wait until rising_edge(clk1x); end loop;
            ioctl_download <= '0';
            report "download index " & integer'image(idx) & ": " & integer'image(a) & " bytes of " & name;
         end procedure;
      begin
         wait for 2 us;
         init_ld <= '0';
         wait for 100 us;
         tb_reset <= '0';
         wait for PRE_RUN_US * 1 us;
         send(0, BIOS_FILE, -1);
         wait for GAP_US * 1 us;
         send(2, KEYS_BIN, -1);
         wait for GAP_US * 1 us;
         send(3, U30_FILE, FLASH_SKIP);
         if META_FILE'length > 0 then
            wait for GAP_US * 1 us;
            send(4, META_BIN, -1);
            wait for GAP_US * 1 us;
            send(5, CARD_FILE, CARD_SKIP);
         end if;
         wait until rising_edge(clk1x);
         chk        <= true;
         loads_done <= true;
         report "downloads finished";
         wait;
      end process;
   end generate;

   -- startup: SDRAM init, keys and card metadata through the loader port, reset
   process
      file fk     : text;
      variable l  : line;
      variable s2 : string(1 to 2);
      variable lo : std_logic_vector(7 downto 0);
      variable st : file_open_status;
      variable n  : integer;

      function hx(s : string) return std_logic_vector is
         variable v : std_logic_vector(7 downto 0);
         variable d : integer;
      begin
         for i in 1 to 2 loop
            case s(i) is
               when '0' to '9' => d := character'pos(s(i)) - character'pos('0');
               when 'a' to 'f' => d := character'pos(s(i)) - character'pos('a') + 10;
               when 'A' to 'F' => d := character'pos(s(i)) - character'pos('A') + 10;
               when others     => d := 0;
            end case;
            v(11 - 4 * i downto 8 - 4 * i) := std_logic_vector(to_unsigned(d, 4));
         end loop;
         return v;
      end function;

      procedure load_words(name : string; tgt : std_logic_vector(1 downto 0); count : integer) is
      begin
         file_open(st, fk, name, read_mode);
         assert st = open_ok report "cannot open " & name severity failure;
         n := 0;
         while not endfile(fk) and n < count loop
            readline(fk, l); read(l, s2); lo := hx(s2);
            readline(fk, l); read(l, s2);
            wait until rising_edge(clk1x);
            ld_wr <= '1'; ld_target <= tgt; ld_addr <= to_unsigned(n, 11); ld_data <= hx(s2) & lo;
            wait until rising_edge(clk1x);
            ld_wr <= '0';
            wait until rising_edge(clk1x);
            n := n + 2;
         end loop;
         file_close(fk);
      end procedure;
   begin
      if LOAD_MODE = 1 then
         wait until loads_done;
      else
         wait for 2 us;
         init_pre <= '0';
         wait for 100 us;          -- EEPROM erase and SDRAM init settle
         load_words(KEY_FILE, "00", 16);
         if META_FILE'length > 0 then
            load_words(META_FILE, "01", 1024);
            card_present <= '1';
         end if;
         wait for 10 us;
         reset_pre <= '0';
         report "reset released";
      end if;
      -- VRAM dumps at the first vertical sync after each DUMP_MS mark, so a
      -- dump holds completed frames as MAME's frame-boundary dumps do
      for k in 1 to RUN_MS / DUMP_MS loop
         wait for DUMP_MS * 1 ms;
         wait until rising_edge(vsync) for 20 ms;
         dump_req <= k * DUMP_MS;
      end loop;
      wait for (RUN_MS mod DUMP_MS) * 1 ms + 1 ms;
      report "run finished";
      done_sim <= true;
      wait;
   end process;

   process (vsync)
   begin
      if rising_edge(vsync) then frames <= frames + 1; end if;
   end process;

   -- ---------------------------------------------------------------- logs
   blk_log : block
      alias gpu_wr   is << signal .tb_zn2_system.dut.bus_gpu_write     : std_logic >>;
      alias gpu_addr is << signal .tb_zn2_system.dut.bus_gpu_addr      : unsigned(3 downto 0) >>;
      alias gpu_data is << signal .tb_zn2_system.dut.bus_gpu_dataWrite : std_logic_vector(31 downto 0) >>;
      alias zreq     is << signal .tb_zn2_system.dut.zn_req   : std_logic >>;
      alias zwe      is << signal .tb_zn2_system.dut.zn_we    : std_logic >>;
      alias zaddr    is << signal .tb_zn2_system.dut.zn_addr  : unsigned(23 downto 0) >>;
      alias zbe      is << signal .tb_zn2_system.dut.zn_be    : std_logic_vector(3 downto 0) >>;
      alias zwdata   is << signal .tb_zn2_system.dut.zn_wdata : std_logic_vector(31 downto 0) >>;
      alias zack     is << signal .tb_zn2_system.dut.zn_ack   : std_logic >>;
      alias zrdata   is << signal .tb_zn2_system.dut.zn_rdata : std_logic_vector(31 downto 0) >>;
      alias pwr      is << signal .tb_zn2_system.dut.bus_pad_write     : std_logic >>;
      alias prd      is << signal .tb_zn2_system.dut.bus_pad_read      : std_logic >>;
      alias paddr    is << signal .tb_zn2_system.dut.bus_pad_addr      : unsigned(3 downto 0) >>;
      alias pwdata   is << signal .tb_zn2_system.dut.bus_pad_dataWrite : std_logic_vector(31 downto 0) >>;
      alias prdata   is << signal .tb_zn2_system.dut.bus_pad_dataRead  : std_logic_vector(31 downto 0) >>;
      alias pc       is << signal .tb_zn2_system.dut.icpu.PC : unsigned(31 downto 0) >>;
      alias rst_i    is << signal .tb_zn2_system.dut.reset_intern : std_logic >>;
      alias ce_i     is << signal .tb_zn2_system.dut.ce : std_logic >>;
      alias paus     is << signal .tb_zn2_system.dut.pausing : std_logic >>;
      alias sspause  is << signal .tb_zn2_system.dut.savestate_pause : std_logic >>;
      alias ssidle   is << signal .tb_zn2_system.dut.SS_idle : std_logic >>;
      alias cpup     is << signal .tb_zn2_system.dut.cpuPaused : std_logic >>;
      alias ss_type  is << signal .tb_zn2_system.dut.isavestates.savetype_counter : integer >>;
      alias ss_count is << signal .tb_zn2_system.dut.isavestates.count : integer >>;
   begin
      process (clk1x, f_clk)
         file fg, fz, fs, fp, fl : text;
         variable l   : line;
         variable opened : boolean := false;
         variable zpend  : boolean := false;
         variable zline  : line;
         variable zcyc   : integer := 0;   -- CPU group cycles from zn_req to zn_ack (zlat.log)
         variable zlab   : line;
         variable prd_1  : std_logic := '0';
         variable nz, ns, ng : integer := 0;
         variable tnext  : time := 100 us;
         variable nddr_rd, nddr_wr : integer := 0;
         function ms(t : time) return string is
         begin
            return integer'image(t / 1 us);
         end function;
      begin
         if not opened then
            file_open(fg, LOGDIR & "/gpu.log", write_mode);
            file_open(fz, LOGDIR & "/zn.log", write_mode);
            file_open(fl, LOGDIR & "/zlat.log", write_mode);
            file_open(fs, LOGDIR & "/sio.log", write_mode);
            file_open(fp, LOGDIR & "/progress.log", write_mode);
            opened := true;
         end if;
         -- the logged signals are in the CPU group: sampled on its clock
         if ((SPLIT = 0 and rising_edge(clk1x)) or (SPLIT = 1 and rising_edge(f_clk))) and reset = '0' then
            if ddr3_RD = '1' then nddr_rd := nddr_rd + 1; end if;
            if ddr3_WE = '1' then nddr_wr := nddr_wr + 1; end if;
            if gpu_wr = '1' then
               write(l, ms(now) & " GP" & integer'image(to_integer(gpu_addr(2 downto 2))) & " " & to_hstring(gpu_data));
               writeline(fg, l); ng := ng + 1;
            end if;
            if zpend then
               zcyc := zcyc + 1;
            end if;
            if zreq = '1' then
               zpend := true;
               zcyc  := 0;
               write(zlab, std_logic'image(zwe) & " " & to_hstring(x"1F" & std_logic_vector(zaddr)) & " " & to_hstring(zbe));
               write(zline, ms(now) & " " & std_logic'image(zwe) & " " & to_hstring(x"1F" & std_logic_vector(zaddr)) &
                            " " & to_hstring(zbe) & " " & to_hstring(zwdata));
            end if;
            if zack = '1' and zpend then
               zpend := false;
               write(zline, " -> " & to_hstring(zrdata));
               writeline(fz, zline); nz := nz + 1;
               write(zlab, " " & integer'image(zcyc));
               writeline(fl, zlab);
            end if;
            if pwr = '1' then
               write(l, ms(now) & " W " & to_hstring(paddr) & " " & to_hstring(pwdata)); writeline(fs, l); ns := ns + 1;
            end if;
            if prd_1 = '1' then
               write(l, ms(now) & " R " & to_hstring(prdata)); writeline(fs, l); ns := ns + 1;
            end if;
            prd_1 := prd;
            if now >= tnext then
               write(l, ms(now) & " us frame " & integer'image(frames) & " PC " & to_hstring(pc) & " gpu " & integer'image(ng) & " zn " & integer'image(nz) &
                        " sio " & integer'image(ns) & " rst " & std_logic'image(rst_i) & " ce " & std_logic'image(ce_i) &
                        " pausing " & std_logic'image(paus) & " sspause " & std_logic'image(sspause) &
                        " ssidle " & std_logic'image(ssidle) & " cpuPaused " & std_logic'image(cpup) &
                        " sstype " & integer'image(ss_type) & " sscount " & integer'image(ss_count) &
                        " ddr3 rd " & integer'image(nddr_rd) & " wr " & integer'image(nddr_wr));
               writeline(fp, l);
               flush(fp); flush(fz); flush(fs); flush(fg); flush(fl);
               tnext := tnext + 100 us;
            end if;
            if wd_reset = '1' then
               write(l, ms(now) & " us WATCHDOG RESET"); writeline(fp, l);
            end if;
         end if;
      end process;

      -- I-cache fill check: sdram.sv raises ch1_ready for a cache line fill
      -- after its second word and writes the last two words into the
      -- I-cache 2 and 4 fast clock edges later. Report any CPU cache read
      -- (cacheHitNext at a CPU clock edge) of a word of the line being
      -- filled that has not been written yet: the CPU would get the old
      -- line contents.
      icheck : block
         alias hitn  is << signal .tb_zn2_system.dut.icpu.cacheHitNext : std_logic >>;
         alias faddr is << signal .tb_zn2_system.dut.icpu.FetchAddr    : unsigned(31 downto 0) >>;
         signal pend      : std_logic_vector(3 downto 0) := "0000";
         signal pend_line : std_logic_vector(7 downto 0) := (others => '0');
         signal nrace     : integer := 0;
      begin
         -- fill start (CPU clock) and word writes (fast clock): one process,
         -- one driver for pend
         process (clk1x, f_clk, clk3x, f_clk2)
            variable p : std_logic_vector(3 downto 0);
         begin
            p := pend;
            if ((SPLIT = 0 and rising_edge(clk3x)) or (SPLIT = 1 and rising_edge(f_clk2))) then
               for i in 0 to 3 loop
                  if cache_wr(i) = '1' and cache_addr = pend_line then p(i) := '0'; end if;
               end loop;
            end if;
            if ((SPLIT = 0 and rising_edge(clk1x)) or (SPLIT = 1 and rising_edge(f_clk))) then
               if ram_ena = '1' and ram_cache = '1' then
                  pend_line <= ram_Adr(11 downto 4);
                  case ram_Adr(3 downto 2) is
                     when "00"   => p := "1111";
                     when "01"   => p := "1110";
                     when "10"   => p := "1100";
                     when others => p := "1000";
                  end case;
               end if;
               if hitn = '1' and std_logic_vector(faddr(11 downto 4)) = pend_line and
                  p(to_integer(faddr(3 downto 2))) = '1' then
                  nrace <= nrace + 1;
                  if nrace < 20 then
                     report "ICACHE RACE: fetch " & to_hstring(faddr) & " reads word " &
                            integer'image(to_integer(faddr(3 downto 2))) & " before its fill write" severity warning;
                  end if;
               end if;
            end if;
            pend <= p;
         end process;
      end block;

      gtrace : if TRACE_US > 0 generate
         process (clk1x, f_clk)
            file ft        : text;
            variable l     : line;
            variable opened : boolean := false;
            variable until_t : time := 0 fs;
            variable pc_1  : unsigned(31 downto 0) := (others => '0');
         begin
            if not opened then
               file_open(ft, LOGDIR & "/trace.log", write_mode);
               opened := true;
            end if;
            if ((SPLIT = 0 and rising_edge(clk1x)) or (SPLIT = 1 and rising_edge(f_clk))) and reset = '0' then
               if zreq = '1' and zwe = '1' and zaddr = x"A10300" and zwdata(7 downto 0) = x"84" then
                  until_t := now + TRACE_US * 1 us;
                  write(l, integer'image(now / 1 us) & " S84"); writeline(ft, l);
               end if;
               if now < until_t then
                  if pc /= pc_1 and not (pc >= x"00002A10" and pc < x"00002A70") then
                     write(l, "P " & to_hstring(pc)); writeline(ft, l);
                  end if;
                  if ram_ena = '1' and ram_rnw = '0' then
                     write(l, "W " & to_hstring(ram_Adr) & " " & to_hstring(ram_dataWrite) & " " & to_hstring(ram_be));
                     writeline(ft, l);
                  end if;
               end if;
               pc_1 := pc;
            end if;
         end process;
      end generate;
   end block;

end architecture;
