// MN10200 decode ROMs (docs/mn10200_design.md 5.3).
// Two synchronous ROMs, generated by tools/mn102/mn102_rom.py from the form
// table in tools/mn102/mn102_isa.py (MN102L manual pp.145-151 with the
// corrections of design study 1.1 and 1.2):
//   form ROM 2048 x 8 : {page, key byte} -> form id   (2 M10K)
//   ctl ROM   256 x 40: form id -> control word       (1 M10K)
// Latency: ctl is valid two clocks after addr.
module mn10200_decode #(
    parameter FORM_HEX = "rtl/zoom/mn10200_form.hex",
    parameter CTL_HEX  = "rtl/zoom/mn10200_ctl.hex"
) (
    input  logic        clk,
    input  logic [10:0] addr,
    output logic [39:0] ctl
);
    logic [7:0]  form_rom [0:2047];
    logic [39:0] ctl_rom  [0:255];
    logic [7:0]  form_q;

    initial begin
        $readmemh(FORM_HEX, form_rom);
        $readmemh(CTL_HEX, ctl_rom);
    end

    always_ff @(posedge clk) begin
        form_q <= form_rom[addr];
        ctl    <= ctl_rom[form_q];
    end
endmodule
