#!/usr/bin/env python3
"""Generate the Verilator top (fs_top.sv) for the full-system simulation
(docs/fullsys_sim.md): psx_top from the GHDL netlist, wired to the sdram.sv
copy as PSX.sv does (ch1 reads, ch2 writes, DMA FIFO, cache fill), and every
other psx_top port passed to the top boundary under its own name, so the C++
harness drives the inputs (constants as in PSX.sv with GNET_LEAN) and reads
the outputs. The SDRAM chip pins (sd_*) and sdram ch3 (loader/flash port)
are top ports too. Debug probes read internal nets by hierarchical name.

    gen_top.py <netlist.v> <out.sv>
"""
import os, re, sys

net, out = sys.argv[1], sys.argv[2]
t = open(net).read()
i = t.index('\nmodule psx_top\n')
hdr = t[i:t.index(');', i)]
ports = re.findall(r'(input|output)\s+(\[\d+:\d+\])?\s*(\w+)', hdr)
names = {p[2] for p in ports}

# psx_top ports wired to the SDRAM controller inside the top (PSX.sv 1291-1360)
internal = {
    'ram_refresh', 'ram_dataWrite', 'ram_dataRead32', 'ram_Adr', 'ram_cntDMA', 'ram_be', 'ram_rnw',
    'ram_ena', 'ram_dma', 'ram_cache', 'ram_done', 'ram_dmafifo_adr', 'ram_dmafifo_data',
    'ram_dmafifo_empty', 'ram_dmafifo_read', 'cache_wr', 'cache_data', 'cache_addr', 'dma_wr',
    'dma_reqprocessed', 'dma_data',
}
# ZN-2 board (zn2-layer psx_top, ZN2_BOARD = 1): the gnet_fc flash port is
# sdram ch3 (PSX.sv GNET_ZN2), as in sim/zn2/system/gen_tb.py
zn2 = 'zn_fl_req' in names
dl = zn2 and os.environ.get('FS_DL') == '1'
if zn2:
    internal |= {'zn_fl_req', 'zn_fl_rnw', 'zn_fl_addr', 'zn_fl_din', 'zn_fl_be', 'zn_fl_ready', 'zn_fl_dout'}
DL_INTERNAL = {'reset', 'zn_ld_wr', 'zn_ld_target', 'zn_ld_addr', 'zn_ld_data', 'zn_card_dl_wr',
               'zn_card_dl_addr', 'zn_card_dl_data', 'zn_card_dl_busy', 'zn_card_present', 'zn_key_valid',
               'zn_dsw', 'zn_jp1', 'zn_wd_reset'}
if dl:
    internal |= DL_INTERNAL
# Taito Zoom (zoom-into-z1, PSX.sv GNET_ZOOM + GNET_ZOOM_SDRAM): the line port
# goes through zoom_sdram_link to zn2_ch3_arb port c (both GHDL extra tops)
zoom = 'zoom_m_req' in names and os.environ.get('FS_ZOOM') == '1'
# gnet-full (PSX.sv GNET_DDR3_ARB): fs_ddr3arb.svh
ddrarb = zoom and os.environ.get('FS_DDR3ARB') == '1'
if zoom:
    internal |= {'zoom_m_req', 'zoom_m_line', 'zoom_m_ready', 'zoom_m_rvalid', 'zoom_m_rdata', 'zoom_rst'}
L = []
L.append('// Generated by sim/fullsys/gen_top.py; do not edit.')
L.append('/* verilator lint_off WIDTHEXPAND */\n/* verilator lint_off WIDTHTRUNC */\n/* verilator lint_off PINCONNECTEMPTY */')
L.append('module fs_top (')
io = []
for d, w, n in ports:
    if n in internal:
        continue
    io.append(f'   {d} {w or ""} {n}')
io += [
    '   input sdram_init',
    '   output [15:0] sd_dq_w', '   input [15:0] sd_dq_r', '   output [12:0] sd_a', '   output [1:0] sd_ba',
    '   output sd_ncs', '   output sd_nwe', '   output sd_nras', '   output sd_ncas',
    '   output [31:0] dbg_pc', '   output dbg_gpu_write', '   output [3:0] dbg_gpu_addr', '   output [31:0] dbg_gpu_data',
]
import os
zn2 = 'zn_fl_req' in names
gp = '_p' if re.search(r'\bwire\s+bus_gpu_write_p;', t) else ''
probes = []
pf = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'probes.txt')
for line in open(pf):
    line = line.split('#')[0].split()
    if len(line) == 3 or (len(line) == 4 and ((line[3] == 'zn2' and zn2) or (line[3] == 'zoom' and zoom))):
        probes.append((line[0], int(line[1]), line[2].replace('@GP@', gp)))
io += [f'   output [{w - 1}:0] dbg_{n}' for n, w, p in probes]
if dl:
    io += ['   input RESET', '   input ioctl_download', '   input [15:0] ioctl_index', '   input [26:0] ioctl_addr',
           '   input [15:0] ioctl_dout', '   input ioctl_wr', '   output reg ioctl_wait', '   output dbg_reset']
if not zn2:
    io += ['   input [26:0] ch3_addr', '   output [31:0] ch3_dout', '   input [31:0] ch3_din', '   input ch3_req',
           '   input ch3_rnw', '   input [3:0] ch3_be', '   output ch3_ready']
L.append(',\n'.join(io))
L.append(');')
for d, w, n in ports:
    if n in internal and not (dl and n in DL_INTERNAL):
        L.append(f'wire {w or ""} {n};')
L.append('wire ch1_ready, ch2_ready;')
if ddrarb and not dl:
    for d, w, n in ports:
        if n.startswith('ddr3_'):
            L.append(f'wire {w or ""} core_{n};')
    L.append(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fs_ddr3arb.svh')).read())
elif zoom and not dl:
    L.append('wire [26:0] ch3_addr; wire [31:0] ch3_din; wire ch3_req, ch3_rnw; wire [3:0] ch3_be; wire ch3_ready; wire [31:0] ch3_dout;')
    L.append('wire zoom_fl_req, zoom_fl_ready; wire [26:0] zoom_fl_addr;')
    L.append("zn2_ch3_arb ich3arb (.clk(clk_cpu), .a_req(1'b0), .a_addr(27'd0), .a_din(32'd0), .a_rnw(1'b0), .a_be(4'd0), .a_ready(),")
    L.append('   .b_req(zn_fl_req), .b_addr(zn_fl_addr), .b_din(zn_fl_din), .b_rnw(zn_fl_rnw), .b_be(zn_fl_be), .b_ready(zn_fl_ready),')
    L.append("   .c_req(zoom_fl_req), .c_addr(zoom_fl_addr), .c_din(32'd0), .c_rnw(1'b1), .c_be(4'hf), .c_ready(zoom_fl_ready),")
    L.append('   .ch3_req(ch3_req), .ch3_addr(ch3_addr), .ch3_din(ch3_din), .ch3_rnw(ch3_rnw), .ch3_be(ch3_be), .ch3_ready(ch3_ready));')
    L.append('assign zn_fl_dout = ch3_dout;')
    L.append('zoom_sdram_link izsl (.clk_cpu(clk_cpu), .clk1x(clk1x), .p_board_rst(zoom_rst), .p_m_req(zoom_m_req), .p_m_line(zoom_m_line),')
    L.append('   .p_m_ready(zoom_m_ready), .p_m_rvalid(zoom_m_rvalid), .p_m_rdata(zoom_m_rdata),')
    L.append('   .c_fl_req(zoom_fl_req), .c_fl_addr(zoom_fl_addr), .c_fl_ready(zoom_fl_ready), .c_fl_dout(ch3_dout));')
elif zn2 and not dl and 'clk_cpu' in names and os.environ.get('FS_CPU50') == '1':
    # ZN-2 board in the CPU group: PSX.sv's zn2_ch3_arb sits between the
    # flash port and ch3 (fs_ch3_arb.sv, the download side tied off)
    L.append('wire [26:0] ch3_addr; wire [31:0] ch3_din; wire ch3_req, ch3_rnw; wire [3:0] ch3_be; wire ch3_ready; wire [31:0] ch3_dout;')
    L.append("fs_ch3_arb ich3arb (.clk(clk_cpu), .a_req(1'b0), .a_addr(27'd0), .a_din(32'd0), .a_rnw(1'b0), .a_be(4'd0), .a_ready(),")
    L.append('   .b_req(zn_fl_req), .b_addr(zn_fl_addr), .b_din(zn_fl_din), .b_rnw(zn_fl_rnw), .b_be(zn_fl_be), .b_ready(zn_fl_ready),')
    L.append('   .ch3_req(ch3_req), .ch3_addr(ch3_addr), .ch3_din(ch3_din), .ch3_rnw(ch3_rnw), .ch3_be(ch3_be), .ch3_ready(ch3_ready));')
    L.append('assign zn_fl_dout = ch3_dout;')
elif zn2 and not dl:
    L.append('wire [26:0] ch3_addr = zn_fl_addr; wire [31:0] ch3_din = zn_fl_din; wire ch3_req = zn_fl_req;')
    L.append('wire ch3_rnw = zn_fl_rnw; wire [3:0] ch3_be = zn_fl_be; wire ch3_ready; wire [31:0] ch3_dout;')
    L.append('assign zn_fl_ready = ch3_ready; assign zn_fl_dout = ch3_dout;')
if dl:
    L.append(open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'fs_psxdl.svh')).read())
L.append('assign ram_done = ch1_ready | ch2_ready;')
L.append('psx_top u (')
L.append(',\n'.join(f'   .{n}(' + (('core_' + n) if (ddrarb and n.startswith('ddr3_')) else n) + ')' for d, w, n in ports))
L.append(');')
cpu50 = 'clk_cpu' in names and os.environ.get('FS_CPU50') == '1'
L.append('''sdram #(.CLK_FAST_RATIO(%s)) isdram (''' % ('2' if cpu50 else '3') if 'clk_cpu' in names else "sdram isdram (")
L.append('''
   .init(sdram_init), .clk(%s), .clk_base(%s), .SDRAM_EN(1'b1),
   .SDRAM_DQ(sd_dq_w), .SDRAM_DQ_IN(sd_dq_r), .SDRAM_A(sd_a), .SDRAM_DQML(), .SDRAM_DQMH(), .SDRAM_BA(sd_ba),
   .SDRAM_nCS(sd_ncs), .SDRAM_nWE(sd_nwe), .SDRAM_nRAS(sd_nras), .SDRAM_nCAS(sd_ncas), .SDRAM_CKE(), .SDRAM_CLK(),
   .refreshForce(ram_refresh), .ram_idle(),
   .ch1_addr({2'b00, ram_Adr}), .ch1_dout(), .ch1_dout32(ram_dataRead32), .ch1_din(16'd0),
   .ch1_req(ram_ena & ram_rnw), .ch1_rnw(1'b1), .ch1_dma(ram_dma), .ch1_cntDMA(ram_cntDMA), .ch1_cache(ram_cache),
   .ch1_ready(ch1_ready), .cache_wr(cache_wr), .cache_data(cache_data), .cache_addr(cache_addr),
   .dma_wr(dma_wr), .dma_reqprocessed(dma_reqprocessed), .dma_data(dma_data),
   .ch2_addr({2'b00, ram_Adr}), .ch2_dout(), .ch2_din(ram_dataWrite), .ch2_req(ram_ena & ~ram_rnw), .ch2_rnw(1'b0),
   .ch2_be(ram_be), .ch2_ready(ch2_ready),
   .ch3_addr(ch3_addr), .ch3_dout(ch3_dout), .ch3_din(ch3_din), .ch3_req(ch3_req), .ch3_rnw(ch3_rnw), .ch3_be(ch3_be),
   .ch3_ready(ch3_ready),
   .dmafifo_adr({4'b0000, ram_dmafifo_adr}), .dmafifo_data(ram_dmafifo_data), .dmafifo_empty(ram_dmafifo_empty),
   .dmafifo_read(ram_dmafifo_read)
);''' % (('clk_cpu2x', 'clk_cpu') if cpu50 else ('clk3x', 'clk1x')))
# GPU-side copies (_p) on branch r1-cpu50: with CPU_CLK_SPLIT = 1 the plain
# names are in the CPU group; the harness logs on clk1x like the GPU
gp = '_p' if re.search(r'\bwire\s+bus_gpu_write_p;', t) else ''
L.append('assign dbg_pc = u.icpu.pc;')
L.append(f'assign dbg_gpu_write = u.bus_gpu_write{gp};')
L.append(f'assign dbg_gpu_addr = u.bus_gpu_addr{gp};')
L.append(f'assign dbg_gpu_data = u.bus_gpu_datawrite{gp};')
for n, w, p in probes:
    L.append(f'assign dbg_{n} = {p};')
L.append('endmodule')
open(out, 'w').write('\n'.join(L) + '\n')

# fs_defaults.h: constant inputs as PSX.sv sets them with GNET_LEAN (and
# GNET_ZN2 where the port exists); everything not listed stays 0.
DEFAULTS = {
    'SPUon': 1, 'videoout_on': 1, 'ram8mb': 1, 'syncVideoOut': 0, 'isPal': 0, 'pal60': 0,
    'biosregion': 0, 'region': 0, 'hasCD': 0, 'fastboot': 0, 'SPUSDRAM': 0, 'REPRODUCIBLEGPUTIMING': 0,
    'spuram_done': 0, 'memcard1_available': 0, 'memcard2_available': 0, 'LIDopen': 0,
    # ZN-2 inputs (sim/zn2/system/gen_tb.py): inputs released, DIP S551 off
    'zn_dsw': 0xF, 'zn_card_dl_wr': 0,
}
hdr_lines = ['// Generated by sim/fullsys/gen_top.py; do not edit.', '#pragma once',
             'template <class T> static void fs_set_defaults(T* t) {']
for d, w, n in ports:
    if n in internal:
        continue
    if d == 'input' and n in DEFAULTS:
        hdr_lines.append(f'   t->{n} = {DEFAULTS[n]};')
    elif d == 'input' and n.startswith('zn_in_'):
        hdr_lines.append(f'   t->{n} = 0xFF;')
    elif d == 'input':
        # any other input (optional ports of newer trees, e.g. zoom_hold):
        # a defined 0 before the harness drives its own, as --x-initial
        # unique would otherwise start it random
        m = re.match(r'\[(\d+):(\d+)\]', (w or '').strip())
        if not m or int(m.group(1)) - int(m.group(2)) < 64:
            hdr_lines.append(f'   t->{n} = 0;')
hdr_lines.append('}')
hdr_lines.append('template <class T> static void fs_print_probes(FILE* f, T* t) {')
for n, w, p in probes:
    if not n.startswith('zn') and not n.startswith('cpu') and not n.startswith('zm'):
        hdr_lines.append(f'   fprintf(f, " {n} %llx", (unsigned long long)t->dbg_{n});')
hdr_lines.append('}')
hdr_lines.append('#define FS_HAS_ZN2 %d' % (1 if zn2 else 0))
hdr_lines.append('#define FS_HAS_ZOOM %d' % (1 if zoom else 0))
hdr_lines.append('#define FS_HAS_DDR3ARB %d' % (1 if ddrarb else 0))
hdr_lines.append('#define FS_HAS_DL %d' % (1 if dl else 0))
hdr_lines.append('#define FS_HAS_CPUCLK %d' % (1 if 'clk_cpu' in names else 0))
open(out.rsplit('/', 1)[0] + '/fs_defaults.h', 'w').write('\n'.join(hdr_lines) + '\n')
print(f'{out}: {len(ports)} psx_top ports, {len(ports) - len(internal & names)} at the top')
