#!/usr/bin/env python3
"""Write SystemVerilog stand-ins for the modules a Verilator lint of PSX.sv
cannot read, so that it elaborates the whole emu module (undeclared names,
port widths, multiple drivers) instead of stopping at the first missing
module:

    lint_stubs.py <out.sv>

- VHDL entities PSX.sv instantiates (psx_mister, zn2_ch3_arb,
  zoom_sdram_link, cdc_handshake): generated from their entity declarations
  (generics as parameters, ports with their ranges, outputs tied to 0)
- framework and Altera blocks (pll_cpu, pll_0002, pll_vid_fixed,
  altddio_out, cyclonev_clkena): fixed stubs with the ports PSX.sv and sys use
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
VHDL = {"psx_mister": "rtl/psx_mister.vhd", "zn2_ch3_arb": "rtl/gnet/zn2_ch3_arb.vhd",
        "zoom_sdram_link": "rtl/gnet/zoom_sdram_link.vhd", "cdc_handshake": "rtl/gnet/cdc/cdc_handshake.vhd"}

FIXED = """
module pll_cpu (input refclk, input rst, output outclk_0, output outclk_1, output locked);
  assign outclk_0 = refclk; assign outclk_1 = refclk; assign locked = 1'b1;
endmodule
module pll_0002 (input refclk, input rst, output outclk_0, output outclk_1, output outclk_2, output locked);
  assign outclk_0 = refclk; assign outclk_1 = refclk; assign outclk_2 = refclk; assign locked = 1'b1;
endmodule
module pll_vid_fixed (input refclk, input rst, output outclk_0, output locked);
  assign outclk_0 = refclk; assign locked = 1'b1;
endmodule
module cyclonev_clkena #(parameter clock_type = "", parameter ena_register_mode = "")
  (input inclk, input ena, output enaout, output outclk);
  assign outclk = inclk; assign enaout = ena;
endmodule
module altddio_out #(parameter extend_oe_disable = "", parameter intended_device_family = "",
  parameter invert_output = "", parameter lpm_hint = "", parameter lpm_type = "", parameter oe_reg = "",
  parameter power_up_high = "", parameter width = 1)
  (input [width-1:0] datain_h, input [width-1:0] datain_l, input outclock, input outclocken,
   input aclr, input aset, input oe, input sclr, input sset, output [width-1:0] dataout, output oe_out);
  assign dataout = datain_h; assign oe_out = oe;
endmodule
"""


PSX = re.sub(r"//[^\n]*", "", open(os.path.join(ROOT, "PSX.sv")).read())


def ventity(name, path):
    t = open(os.path.join(ROOT, path)).read()
    t = re.sub(r"--[^\n]*", "", t)
    e = re.search(r"\bentity\s+%s\s+is(.*?)\bend\s+(entity|%s)" % (name, name), t, re.S | re.I).group(1)
    params, ports = [], []
    # PSX.sv's spelling of the ports it connects on this module (VHDL names
    # are case-insensitive)
    spell = {}
    for inst in re.finditer(r"\b%s\b\s*(#\s*\(.*?\)\s*)?\w+\s*\((.*?)\);" % name, PSX, re.S):
        spell.update({n.lower(): n for n in re.findall(r"\.(\w+)\s*\(", inst.group(2))})
    g = re.search(r"\bgeneric\s*\((.*?)\)\s*;\s*port\b", e, re.S | re.I)
    if g:
        for d in g.group(1).split(";"):
            m = re.match(r"\s*(\w+)\s*:\s*(\w+)(?:\s*:=\s*(.+))?", d, re.S)
            if m:
                v = (m.group(3) or "0").strip()
                if m.group(2).lower() == "time":
                    v = "0"
                v = re.sub(r"16#(\w+)#", r"'h\1", v)
                v = re.sub(r"^'([01])'$", r"1'b\1", v)
                v = re.sub(r'^x"(\w+)"$', r"'h\1", v)
                v = {"true": "1", "false": "0"}.get(v.lower(), v)
                params.append(f"parameter {m.group(1)} = {v}")
    p = re.search(r"\bport\s*\((.*)\)\s*;", e, re.S | re.I).group(1)
    for d in p.split(";"):
        m = re.match(r"\s*([\w\s,]+?)\s*:\s*(in|out|inout|buffer)\s+(\w+)\s*(\(([^)]*)\))?", d, re.S | re.I)
        if not m:
            continue
        rng = ""
        if m.group(5):
            mm = re.match(r"\s*(.+?)\s+downto\s+(.+)", m.group(5), re.I)
            if mm:
                rng = f"[{mm.group(1)}:{mm.group(2)}] "
        dirn = {"in": "input", "out": "output", "inout": "inout", "buffer": "output"}[m.group(2).lower()]
        for n in m.group(1).split(","):
            n = n.strip()
            ports.append((dirn, rng, spell.get(n.lower(), n)))
    s = f"module {name}"
    if params:
        s += " #(" + ", ".join(params) + ")"
    s += " (\n  " + ",\n  ".join(f"{d} logic {r}{n}" for d, r, n in ports) + "\n);\n"
    for d, r, n in ports:
        if d == "output":
            s += f"  assign {n} = '0;\n"
    return s + "endmodule\n"


def main():
    out = open(sys.argv[1], "w")
    out.write("// generated by sim/zoomlink/lint_stubs.py: lint stand-ins, not RTL\n/* verilator lint_off UNUSEDSIGNAL */\n")
    out.write(FIXED)
    for n, p in VHDL.items():
        out.write(ventity(n, p))
    out.close()


if __name__ == "__main__":
    main()
