#!/usr/bin/env python3
"""Make a small VHDL entity that holds psx_top.vhd's clk3xIndex generator, so
the memory bench can drive dma.vhd with the generator as written in the RTL.

The text is copied, not rewritten: from the "-- clock index" section of
rtl/psx_top.vhd (up to "-- busses") it takes every process clocked by clk1x
or clk3x (the clk1xToggle flip and the clk3xIndex generator) and every
concurrent assert, plus the declarations of the signals they use. The clk2x
process (clk2xIndex) is left out. The entity has the psx_top generic
CLK_FAST_RATIO, inputs clk1x and clk3x, and output clk3xIndex_o.

    psx_top_index_copy.py <rtl/psx_top.vhd> <out.vhd>
"""
import re
import sys

SIGNALS = ["clk1xToggle", "clk1xToggle3X", "clk1xToggle3X_1", "clk3xIndex"]


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src = open(sys.argv[1]).read().split("\n")
    start = next(i for i, l in enumerate(src) if l.strip() == "-- clock index")
    end = next(i for i in range(start, len(src)) if src[i].strip() == "-- busses")
    sec = src[start:end]

    parts = []
    i = 0
    while i < len(sec):
        l = sec[i]
        m = re.match(r"\s*process\s*\((\w+)\)", l)
        if m:
            j = next(k for k in range(i, len(sec)) if sec[k].strip() == "end process;")
            if m.group(1) in ("clk1x", "clk3x"):
                parts.append("\n".join(sec[i:j + 1]))
            i = j + 1
            continue
        if re.match(r"\s*assert\b", l):
            parts.append(l)
        i += 1
    body = "\n\n".join(parts)
    if "clk3xIndex" not in body or "CLK_FAST_RATIO" not in body:
        sys.exit("psx_top_index_copy: generator not found, psx_top.vhd changed?")

    decls = []
    for s in SIGNALS:
        d = [l for l in src if re.match(r"\s*signal\s+" + s + r"\s*:", l)]
        if len(d) != 1:
            sys.exit(f"psx_top_index_copy: declaration of {s} not found once")
        decls.append(d[0])

    out = f"""-- generated by tools/r1/mem_lat/psx_top_index_copy.py from {sys.argv[1]}
library ieee;
use ieee.std_logic_1164.all;

entity clk3x_index_copy is
   generic (CLK_FAST_RATIO : integer := 3);
   port (clk1x, clk3x : in std_logic; clk3xIndex_o : out std_logic);
end entity;

architecture copy of clk3x_index_copy is
{chr(10).join(decls)}
begin

{body}

   clk3xIndex_o <= clk3xIndex;

end architecture;
"""
    open(sys.argv[2], "w").write(out)


if __name__ == "__main__":
    main()
