#!/usr/bin/env python3
"""Build the G-NET web converter: one self-contained HTML file.

  python3 web/converter/build.py

Reads the source in web/converter/src/ and the game tables (SETS, BIOS_PARTS,
CARD_MAX, CARD_TYPE_NAME) from tools/gnet/gnet_tester_zips.py, so the page
always knows the same games as the command-line converter. Writes:

  web/converter/dist/index.html             the converter page (everything inline,
                                            works from a web server or opened as a file)
  tools/gnet_converter.html                 the same page, committed, for people who
                                            download it and open it from disk
  web/converter/build/modules/*.js          the same code as ES modules, with
                                            tables.js, for the Node test
                                            (web/converter/test/verify_node.mjs)

Both output folders are generated (gitignored). Cloudflare Pages: build command
"python3 web/converter/build.py", build output directory "web/converter/dist".
Python 3 standard library only.
"""
import hashlib
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SRC = os.path.join(HERE, "src")
DIST = os.path.join(HERE, "dist")
MODULES = os.path.join(HERE, "build", "modules")
TESTER = os.path.join(REPO, "tools", "gnet", "gnet_tester_zips.py")

# lib modules in dependency order
ORDER = ["util", "lzma", "flac", "chd", "zip", "buildflash", "tables", "convert"]


def load_tester():
    sys.path.insert(0, os.path.dirname(TESTER))
    sys.path.insert(1, os.path.dirname(os.path.dirname(TESTER)))
    spec = importlib.util.spec_from_file_location("gnet_tester_zips", TESTER)
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def tables_js(m):
    sets = {}
    for s, (title, chd_name, sha1, ctype, parent) in m.SETS.items():
        sets[s] = {"title": title, "chd": chd_name, "sha1": sha1, "card_type": ctype, "parent": parent}
    src_hash = hashlib.sha256(open(TESTER, "rb").read()).hexdigest()[:12]
    return ("// Generated by web/converter/build.py from tools/gnet/gnet_tester_zips.py. Do not edit.\n"
            f"export const SETS = {json.dumps(sets, indent=1, ensure_ascii=False)};\n"
            f"export const BIOS_PARTS = {json.dumps(m.BIOS_PARTS)};\n"
            f"export const CARD_MAX = {m.CARD_MAX};\n"
            f"export const CARD_TYPE_NAME = {json.dumps({str(k): v for k, v in m.CARD_TYPE_NAME.items()})};\n"
            f"export const TABLES_SOURCE = {json.dumps('gnet_tester_zips.py sha256 ' + src_hash)};\n")


IMPORT_RE = re.compile(r'^import \{([^}]*)\} from "\./([a-z]+)\.js";\n', re.M)
EXPORT_RE = re.compile(r"^export (?:async function\*?|function\*?|class|const|let) +([A-Za-z_$][\w$]*)", re.M)


def bundle(sources):
    """ES modules -> one classic script: each module in its own function
    scope, imports turned into destructuring, all exports gathered in GNET"""
    out = ["\"use strict\";"]
    for name in ORDER:
        code = sources[name]
        exports = EXPORT_RE.findall(code)
        imports = IMPORT_RE.findall(code)
        code = IMPORT_RE.sub("", code)
        code = re.sub(r"^export ", "", code, flags=re.M)
        if "export" in re.sub(r"//.*|\"[^\"]*\"", "", code).split():
            sys.exit(f"build: {name}.js has an export form the bundler does not handle")
        head = "".join(f"  const {{{names.strip()}}} = __m_{dep};\n" for names, dep in imports)
        out.append(f"const __m_{name} = (() => {{\n{head}{code}\nreturn {{ {', '.join(exports)} }};\n}})();")
    out.append("const GNET = Object.freeze(Object.assign({}, " + ", ".join(f"__m_{n}" for n in ORDER) + "));")
    return "\n".join(out) + "\n"


def main():
    m = load_tester()
    sources = {}
    for name in ORDER:
        if name == "tables":
            sources[name] = tables_js(m)
        else:
            with open(os.path.join(SRC, "lib", name + ".js"), encoding="utf-8") as f:
                sources[name] = f.read()
    shutil.rmtree(MODULES, ignore_errors=True)
    os.makedirs(MODULES)
    for name, code in sources.items():
        with open(os.path.join(MODULES, name + ".js"), "w", encoding="utf-8") as f:
            f.write(code)
    lib = bundle(sources)
    read = lambda p: open(os.path.join(SRC, p), encoding="utf-8").read()  # noqa: E731
    page = read("index.html")
    for tag, text in (("STYLE", read("style.css")), ("LIB", lib), ("WORKER", read("worker.js")), ("APP", read("app.js"))):
        marker = f"/*@{tag}@*/"
        if page.count(marker) != 1:
            sys.exit(f"build: {marker} must appear once in src/index.html")
        if "</script" in text.lower() or "</style" in text.lower():
            sys.exit(f"build: {tag} source contains a closing tag")
        page = page.replace(marker, text)
    tables_version = re.search(r'TABLES_SOURCE = "([^"]*)"', sources["tables"]).group(1)
    try:
        rev = subprocess.run(["git", "-C", REPO, "rev-parse", "--short", "HEAD"], capture_output=True,
                             text=True).stdout.strip()
    except OSError:
        rev = ""
    page = page.replace("@BUILD@", "Build: " + (f"{rev}, " if rev else "") + tables_version + ".")
    shutil.rmtree(DIST, ignore_errors=True)
    os.makedirs(DIST)
    for out in (os.path.join(DIST, "index.html"), os.path.join(REPO, "tools", "gnet_converter.html")):
        with open(out, "w", encoding="utf-8") as f:
            f.write(page)
    print(f"wrote {os.path.relpath(os.path.join(DIST, 'index.html'), REPO)} ({len(page.encode()):,} bytes, "
          f"{len(m.SETS)} sets) and {os.path.relpath(MODULES, REPO)}/")


if __name__ == "__main__":
    main()
