#!/usr/bin/env python3
"""Write empty SystemVerilog modules with the generics and ports of VHDL
entities, so that Verilator can lint PSX.sv's connections to them (port
names, directions, widths). Used by sim/dbg/lint_psx.sh.

Usage: vhdl_stub.py [--case-from file.sv] out.sv file.vhd[:entity] ...

VHDL names are case-insensitive and Quartus matches them that way from
Verilog; Verilator does not. With --case-from, a port whose name differs
only in case from a named connection .name( in that file, and is not
itself spelled that way anywhere in it, is spelled as the connection.

Handles the port types used at the PSX.sv boundary: std_logic,
std_logic_vector / unsigned / signed with (a downto b), integer and
natural (32 bits). Anything else becomes one bit with a comment.
"""
import re
import sys


def strip_comments(text):
    return "\n".join(l.split("--", 1)[0] for l in text.splitlines())


def find_entity(text, name):
    pat = re.compile(r"\bentity\s+(\w+)\s+is\b(.*?)\bend\b\s*(entity)?\s*(\w+)?\s*;", re.S | re.I)
    for m in pat.finditer(text):
        if name is None or m.group(1).lower() == name.lower():
            return m.group(1), m.group(2)
    raise SystemExit("entity %s not found" % name)


def section(body, kw):
    m = re.search(r"\b%s\s*\(" % kw, body, re.I)
    if not m:
        return ""
    i = m.end()
    depth = 1
    j = i
    while depth:
        if body[j] == "(":
            depth += 1
        elif body[j] == ")":
            depth -= 1
        j += 1
    return body[i:j - 1]


def split_decls(sec):
    out, depth, cur = [], 0, ""
    for ch in sec:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == ";" and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return [d for d in out if d]


def sv_range(typ):
    m = re.search(r"\(\s*(.+?)\s+downto\s+(.+?)\s*\)", typ, re.I)
    if m:
        return "[%s:%s] " % (m.group(1).strip(), m.group(2).strip())
    if re.match(r"\s*(integer|natural|positive)\b", typ, re.I):
        return "[31:0] "
    return ""


def main():
    args = sys.argv[1:]
    case = {}
    exact = set()
    if args[0] == "--case-from":
        for n in re.findall(r"\.(\w+)\s*\(", open(args[1]).read()):
            case[n.lower()] = n
            exact.add(n)
        args = args[2:]
    out = args[0]
    mods = []
    for spec in args[1:]:
        path, _, ent = spec.partition(":")
        text = strip_comments(open(path).read())
        name, body = find_entity(text, ent or None)
        params, ports = [], []
        for d in split_decls(section(body, "generic")):
            names, _, rest = d.partition(":")
            typ, _, default = rest.partition(":=")
            default = default.strip() or "0"
            if re.match(r"\s*time\b", typ, re.I) or re.match(r"\s*string\b", typ, re.I) or default.startswith('"'):
                default = "0"
            default = re.sub(r"(\d+)\s*ns\b", r"\1", default)
            if default.startswith("'"):
                default = "1'b" + default[1]
            for n in names.split(","):
                params.append("parameter %s = %s" % (n.strip(), default))
        for d in split_decls(section(body, "port")):
            names, _, rest = d.partition(":")
            rest = rest.split(":=")[0].strip()
            mdir, _, typ = rest.partition(" ")
            mdir = mdir.lower()
            sv_dir = {"in": "input", "out": "output", "buffer": "output", "inout": "inout"}[mdir]
            rng = sv_range(typ)
            for n in names.split(","):
                n = n.strip()
                if n not in exact:
                    n = case.get(n.lower(), n)
                ports.append("    %s wire %s%s" % (sv_dir, rng, n))
        hdr = "module %s" % name
        if params:
            hdr += " #(\n    " + ",\n    ".join(params) + "\n)"
        mods.append(hdr + " (\n" + ",\n".join(ports) + "\n);\nendmodule\n")
    open(out, "w").write("// generated by sim/dbg/vhdl_stub.py, lint only\n/* verilator lint_off UNUSED */\n/* verilator lint_off UNDRIVEN */\n" + "\n".join(mods))


if __name__ == "__main__":
    main()
