#!/usr/bin/env python3
"""Pull the shell's pause and watchdog-mask logic out of PSX.sv into
work/pausewd_psx.svh for tb_pausewd.sv, so the bench runs PSX.sv's own
text: GNET_WD_TIMEOUT_S, the zn_wd_hold block, the pause/reset block
(paused, button pause, OSD pause, unpause, reset), GNET_WD_GRACE, the
grace counter and zn_wd_mask. Fails if a block is not found."""
import re, sys, pathlib
root = pathlib.Path(__file__).resolve().parents[2]
src = (root / 'PSX.sv').read_text()

def block(start):
    i = src.find(start)
    if i < 0:
        sys.exit(f'gen_pausewd: not found: {start!r}')
    j = src.find('\nend\n', i)
    return src[i:j + 5]

def line(pat):
    m = re.search(pat, src, re.M)
    if not m:
        sys.exit(f'gen_pausewd: not found: {pat}')
    return m.group(0) + '\n'

out = [
    '// generated by sim/shell/gen_pausewd.py from PSX.sv; do not edit\n',
    line(r'^localparam GNET_WD_TIMEOUT_S = .*;$'),
    block('always @(posedge clk_1x) begin\n\tif (zn_wd_reset & ~status[100] & ~zn_wd_mask)'),
    block('always @(posedge clk_1x) begin\n\n   paused <= 0;'),
    line(r'^localparam \[29:0\] GNET_WD_GRACE = .*;$'),
    line(r'^reg \[29:0\] zn_wd_grace = 0;$'),
    block('always @(posedge clk_1x) begin\n   if (paused)\n      zn_wd_grace <= GNET_WD_GRACE;'),
    line(r'^assign zn_wd_mask = .*;$'),
]
# negative control: "nomask" drops the mask (the pre-shell behaviour),
# "nograce" keeps only the pause itself
if len(sys.argv) > 1 and sys.argv[1] == 'nomask':
    out = [o.replace('assign zn_wd_mask = paused | (zn_wd_grace != 0);', "assign zn_wd_mask = 1'b0;") for o in out]
if len(sys.argv) > 1 and sys.argv[1] == 'nograce':
    out = [o.replace('assign zn_wd_mask = paused | (zn_wd_grace != 0);', 'assign zn_wd_mask = paused;') for o in out]
(pathlib.Path(__file__).parent / 'work').mkdir(exist_ok=True)
(pathlib.Path(__file__).parent / 'work' / 'pausewd_psx.svh').write_text(''.join(out))
print('gen_pausewd: work/pausewd_psx.svh,', sum(o.count('\n') for o in out), 'lines')
