#!/usr/bin/env python3
"""Generate tb_cpu50_system.vhd: psx_top with the G-NET LEAN trims, the real
sdram.sv (R1 simulation copy), an SDRAM chip model preloaded with a BIOS
image (sim/cpu50/smoke_prog.py) and a DDR3 model. The chip and DDR3 models
follow sim/zn2/system/tb_zn2_system.tpl on branch zn2-layer (same author,
reduced: no flash or card areas). Generic SPLIT: 0 = upstream clocking
(clk_cpu ports on clk1x/clk2x/clk3x, SDRAM 3:1 on clk3x/clk1x); 1 =
CPU_CLK_SPLIT with clk_cpu 50.000 MHz and clk_cpu2x 100.000 MHz (SDRAM 2:1
on them), clk1x/clk2x at 33.8688/67.7376 MHz started PHASE later. The bench
logs every RAM write to 0x100-0x11F (the program's results) to ram.log and
the CPU's progress to progress.log. Ports are taken from rtl/psx_top.vhd.

    gen_system_tb.py <rtl/psx_top.vhd> <out.vhd>
"""
import re
import sys

TB_IN = {
    "clk1x": "clk1x", "clk2x": "clk2x", "clk3x": "clk3x", "clkvid": "clkvid",
    "clk_cpu": "c_clk", "clk_cpu2x": "c_clk2", "clk_cpu3x": "c_clk3", "reset": "reset",
    "ram_dataRead32": "ch1_dout32", "ram_done": "ram_done", "ram_dmafifo_read": "dmafifo_read",
    "cache_wr": "cache_wr", "cache_data": "cache_data", "cache_addr": "cache_addr",
    "dma_wr": "dma_wr", "dma_reqprocessed": "dma_reqprocessed", "dma_data": "dma_data",
    "ddr3_BUSY": "ddr3_BUSY", "ddr3_DOUT": "ddr3_DOUT", "ddr3_DOUT_READY": "ddr3_DOUT_READY",
}
TB_OUT = {
    "ram_refresh": "ram_refresh", "ram_dataWrite": "ram_dataWrite", "ram_Adr": "ram_Adr",
    "ram_cntDMA": "ram_cntDMA", "ram_be": "ram_be", "ram_rnw": "ram_rnw", "ram_ena": "ram_ena",
    "ram_dma": "ram_dma", "ram_cache": "ram_cache", "ram_dmafifo_adr": "dmafifo_adr",
    "ram_dmafifo_data": "dmafifo_data", "ram_dmafifo_empty": "dmafifo_empty",
    "ddr3_BURSTCNT": "ddr3_BURSTCNT", "ddr3_ADDR": "ddr3_ADDR", "ddr3_DIN": "ddr3_DIN",
    "ddr3_BE": "ddr3_BE", "ddr3_WE": "ddr3_WE", "ddr3_RD": "ddr3_RD",
}
CONST_ONE = {"SPUon", "videoout_on"}

TEMPLATE = r'''-- Generated by sim/cpu50/gen_system_tb.py from rtl/psx_top.vhd: do not edit.
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use STD.textio.all;

entity sdram_chip_bios is
   generic (BIOS_FILE : string);
   port (
      clk   : in  std_logic;
      ncs, nras, ncas, nwe : in std_logic;
      ba    : in  std_logic_vector(1 downto 0);
      a     : in  std_logic_vector(12 downto 0);
      dq_w  : in  std_logic_vector(15 downto 0);
      dq_r  : out std_logic_vector(15 downto 0)
   );
end entity;

-- 32 MB, word key = ba & row & column = byte address / 2; commands on the
-- falling controller clock edge, CAS latency 2, burst 2
architecture sim of sdram_chip_bios is
begin
   process (clk)
      type t_mem is array(0 to 2**24 - 1) of integer range 0 to 65535;
      type t_mem_ptr is access t_mem;
      variable mem  : t_mem_ptr := null;
      type t_rows is array(0 to 3) of unsigned(12 downto 0);
      variable rows : t_rows := (others => (others => '0'));
      type t_q is array(0 to 4) of std_logic_vector(15 downto 0);
      variable q    : t_q := (others => (others => 'Z'));
      variable key, bank, n : integer;
      variable d    : std_logic_vector(15 downto 0);
      type t_cf is file of character;
      file f        : t_cf;
      variable st   : file_open_status;
      variable c0, c1 : character;
   begin
      if mem = null then
         mem := new t_mem'(others => 0);
         file_open(st, f, BIOS_FILE, read_mode);
         assert st = open_ok report "cannot open " & BIOS_FILE severity failure;
         n := 16#800000# / 2;
         while not endfile(f) loop
            read(f, c0); read(f, c1);
            mem(n) := character'pos(c0) + 256 * character'pos(c1);
            n := n + 1;
         end loop;
         file_close(f);
      end if;
      if falling_edge(clk) then
         for i in 0 to 3 loop q(i) := q(i + 1); end loop;
         q(4) := (others => 'Z');
         if ncs = '0' then
            bank := to_integer(unsigned(ba));
            if nras = '0' and ncas = '1' and nwe = '1' then
               rows(bank) := unsigned(a);
            elsif nras = '1' and ncas = '0' then
               key := to_integer(unsigned(ba) & rows(bank) & unsigned(a(8 downto 0)));
               if nwe = '1' then
                  q(2) := std_logic_vector(to_unsigned(mem(key), 16));
                  key  := to_integer(to_unsigned(key, 24) xor x"000001");
                  q(3) := std_logic_vector(to_unsigned(mem(key), 16));
               else
                  d := std_logic_vector(to_unsigned(mem(key), 16));
                  if a(11) = '0' then d(7 downto 0)  := dq_w(7 downto 0);  end if;
                  if a(12) = '0' then d(15 downto 8) := dq_w(15 downto 8); end if;
                  mem(key) := to_integer(unsigned(d));
               end if;
            end if;
         end if;
         dq_r <= q(0);
      end if;
   end process;
end architecture;

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ddr3_model_small is
   generic (LAT : integer := 15);
   port (
      clk        : in  std_logic;
      busy       : out std_logic := '0';
      burstcnt   : in  std_logic_vector(7 downto 0);
      addr       : in  std_logic_vector(27 downto 0);
      dout       : out std_logic_vector(63 downto 0) := (others => '0');
      dout_ready : out std_logic := '0';
      rd         : in  std_logic;
      din        : in  std_logic_vector(63 downto 0);
      be         : in  std_logic_vector(7 downto 0);
      we         : in  std_logic
   );
end entity;

-- low 16 MB (VRAM, SPU RAM, frame buffers, savestate header area wraps)
architecture sim of ddr3_model_small is
begin
   process
      constant NLOW : integer := 2**21;
      type t_arr is array(natural range <>) of integer;
      type t_arr_ptr is access t_arr;
      variable lo_l, lo_h : t_arr_ptr;
      variable w, bc : integer;
      variable v     : std_logic_vector(63 downto 0);
   begin
      lo_l := new t_arr'(0 to NLOW - 1 => 0);
      lo_h := new t_arr'(0 to NLOW - 1 => 0);
      loop
         wait until rising_edge(clk);
         if rd = '1' then
            w  := to_integer(unsigned(addr(23 downto 3)));
            bc := to_integer(unsigned(burstcnt));
            wait until rising_edge(clk);
            for i in 1 to LAT loop wait until rising_edge(clk); end loop;
            for i in 0 to bc - 1 loop
               dout       <= std_logic_vector(to_signed(lo_h((w + i) mod NLOW), 32)) & std_logic_vector(to_signed(lo_l((w + i) mod NLOW), 32));
               dout_ready <= '1';
               wait until rising_edge(clk);
            end loop;
            dout_ready <= '0';
         elsif we = '1' then
            w := to_integer(unsigned(addr(23 downto 3)));
            v := std_logic_vector(to_signed(lo_h(w), 32)) & std_logic_vector(to_signed(lo_l(w), 32));
            for b in 0 to 7 loop
               if be(b) = '1' then v(8 * b + 7 downto 8 * b) := din(8 * b + 7 downto 8 * b); end if;
            end loop;
            lo_l(w) := to_integer(signed(v(31 downto 0))); lo_h(w) := to_integer(signed(v(63 downto 32)));
         end if;
      end loop;
   end process;
end architecture;

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use STD.textio.all;
use work.pJoypad.all;

entity tb_cpu50_system is
   generic (
      SPLIT     : integer := 1;
      PHASE     : time    := 7 ns;
      BIOS_FILE : string  := "bios.bin";
      RUN_US    : integer := 1500
   );
end entity;

architecture sim of tb_cpu50_system is

   component sdram is
      generic (CLK_FAST_RATIO : integer);
      port (
         init, clk, clk_base, SDRAM_EN : in std_logic;
         SDRAM_DQ    : out std_logic_vector(15 downto 0);
         SDRAM_DQ_IN : in  std_logic_vector(15 downto 0);
         idx_o       : out std_logic;
         SDRAM_A     : out std_logic_vector(12 downto 0);
         SDRAM_DQML, SDRAM_DQMH : out std_logic;
         SDRAM_BA    : out std_logic_vector(1 downto 0);
         SDRAM_nCS, SDRAM_nWE, SDRAM_nRAS, SDRAM_nCAS, SDRAM_CKE, SDRAM_CLK : out std_logic;
         refreshForce : in std_logic;
         ram_idle     : out std_logic;
         ch1_addr : in std_logic_vector(26 downto 0);
         ch1_dout : out std_logic_vector(127 downto 0);
         ch1_dout32 : out std_logic_vector(31 downto 0);
         ch1_din  : in std_logic_vector(15 downto 0);
         ch1_req, ch1_rnw, ch1_dma : in std_logic;
         ch1_cntDMA : in std_logic_vector(1 downto 0);
         ch1_cache : in std_logic;
         ch1_ready : out std_logic;
         cache_wr : out std_logic_vector(3 downto 0);
         cache_data : out std_logic_vector(31 downto 0);
         cache_addr : out std_logic_vector(7 downto 0);
         dma_wr, dma_reqprocessed : out std_logic;
         dma_data : out std_logic_vector(31 downto 0);
         ch2_addr : in std_logic_vector(26 downto 0);
         ch2_dout : out std_logic_vector(31 downto 0);
         ch2_din  : in std_logic_vector(31 downto 0);
         ch2_req, ch2_rnw : in std_logic;
         ch2_be : in std_logic_vector(3 downto 0);
         ch2_ready : out std_logic;
         ch3_addr : in std_logic_vector(26 downto 0);
         ch3_dout : out std_logic_vector(31 downto 0);
         ch3_din  : in std_logic_vector(31 downto 0);
         ch3_req, ch3_rnw : in std_logic;
         ch3_be : in std_logic_vector(3 downto 0);
         ch3_ready : out std_logic;
         dmafifo_adr  : in std_logic_vector(26 downto 0);
         dmafifo_data : in std_logic_vector(31 downto 0);
         dmafifo_empty : in std_logic;
         dmafifo_read : out std_logic
      );
   end component;

   constant JOY0 : joypad_t := ('0','0','0','0','0','0','0','0','0','0','0','0',
                                '0','0','0','0','0','0','0','0','0','0','0','0','0','0','0','0',
                                (others => '1'), (others => '1'), (others => '1'), (others => '1'));

   constant H : time := 2461 ps;   -- 203.2 MHz base: clk3x 4H, clk2x 6H, clk1x 12H

   signal clk1x, clk2x, clk3x : std_logic := '1';
   signal clkvid              : std_logic := '0';
   signal f_clk, f_clk2       : std_logic := '0';   -- CPU PLL (SPLIT = 1)
   signal c_clk, c_clk2, c_clk3 : std_logic;
   signal sd_clk, sd_base     : std_logic;
   signal reset               : std_logic := '1';
   signal sdram_init          : std_logic := '1';
   signal done_sim            : boolean := false;

   signal ram_refresh, ram_rnw, ram_ena, ram_dma, ram_cache : std_logic;
   signal ram_dataWrite       : std_logic_vector(31 downto 0);
   signal ram_Adr             : std_logic_vector(24 downto 0);
   signal ram_cntDMA          : std_logic_vector(1 downto 0);
   signal ram_be              : std_logic_vector(3 downto 0);
   signal ram_done            : std_logic;
   signal ch1_ready, ch2_ready : std_logic;
   signal ch1_dout32          : std_logic_vector(31 downto 0);
   signal dmafifo_adr         : std_logic_vector(22 downto 0);
   signal dmafifo_data        : std_logic_vector(31 downto 0);
   signal dmafifo_empty       : std_logic;
   signal dmafifo_read        : std_logic;
   signal cache_wr            : std_logic_vector(3 downto 0);
   signal cache_data          : std_logic_vector(31 downto 0);
   signal cache_addr          : std_logic_vector(7 downto 0);
   signal dma_wr, dma_reqprocessed : std_logic;
   signal dma_data            : std_logic_vector(31 downto 0);
   signal sd_dq_w, sd_dq_r    : std_logic_vector(15 downto 0);
   signal sd_a                : std_logic_vector(12 downto 0);
   signal sd_ba               : std_logic_vector(1 downto 0);
   signal sd_ncs, sd_nwe, sd_nras, sd_ncas : std_logic;

   signal ddr3_BUSY, ddr3_DOUT_READY, ddr3_WE, ddr3_RD : std_logic;
   signal ddr3_DOUT, ddr3_DIN : std_logic_vector(63 downto 0);
   signal ddr3_BURSTCNT       : std_logic_vector(7 downto 0);
   signal ddr3_ADDR           : std_logic_vector(27 downto 0);
   signal ddr3_BE             : std_logic_vector(7 downto 0);

   function ratio return integer is
   begin
      if SPLIT = 1 then return 2; end if;
      return 3;
   end function;

begin

   -- PS1 clocks: one base, rising edges of clk1x, clk2x and clk3x aligned
   process
      variable k : integer := 0;
   begin
      if SPLIT = 1 then wait for PHASE; end if;
      loop
         wait for H;
         k := k + 1;
         if k mod 2 = 0 then clk3x <= not clk3x; end if;
         if k mod 3 = 0 then clk2x <= not clk2x; end if;
         if k mod 6 = 0 then clk1x <= not clk1x; end if;
         exit when done_sim;
      end loop;
      wait;
   end process;
   clkvid <= not clkvid after 9312 ps when not done_sim;

   -- CPU PLL: 100.000 and 50.000 MHz, phase-aligned
   f_clk2 <= not f_clk2 after 5 ns when not done_sim and SPLIT = 1;
   process (f_clk2)
   begin
      if rising_edge(f_clk2) then f_clk <= not f_clk; end if;
   end process;

   -- the clk_cpu ports carry the same signals as clk1x/clk2x/clk3x when SPLIT = 0
   g0 : if SPLIT = 0 generate
      dut : entity work.psx_top
      generic map (HAS_CD => 0, HAS_PADS => 0, HAS_SAVESTATES => 0, HAS_CHEATS => 0, HAS_MDEC => 0,
                   VRAM_Y_BITS => 10, GTE_NARROW_MUL => 3, CLK_FAST_RATIO => 3, CPU_CLK_SPLIT => 0, is_simu => '1')
      port map (
@PORTMAP0@
      );
      isdram : sdram
      generic map (CLK_FAST_RATIO => 3)
      port map (
         init => sdram_init, clk => clk3x, clk_base => clk1x,
@SDRAMMAP@
      );
      ichip : entity work.sdram_chip_bios
      generic map (BIOS_FILE => BIOS_FILE)
      port map (clk => clk3x, ncs => sd_ncs, nras => sd_nras, ncas => sd_ncas, nwe => sd_nwe,
                ba => sd_ba, a => sd_a, dq_w => sd_dq_w, dq_r => sd_dq_r);
   end generate;

   g1 : if SPLIT = 1 generate
      dut : entity work.psx_top
      generic map (HAS_CD => 0, HAS_PADS => 0, HAS_SAVESTATES => 0, HAS_CHEATS => 0, HAS_MDEC => 0,
                   VRAM_Y_BITS => 10, GTE_NARROW_MUL => 3, CLK_FAST_RATIO => 2, CPU_CLK_SPLIT => 1, is_simu => '1')
      port map (
@PORTMAP1@
      );
      isdram : sdram
      generic map (CLK_FAST_RATIO => 2)
      port map (
         init => sdram_init, clk => f_clk2, clk_base => f_clk,
@SDRAMMAP@
      );
      ichip : entity work.sdram_chip_bios
      generic map (BIOS_FILE => BIOS_FILE)
      port map (clk => f_clk2, ncs => sd_ncs, nras => sd_nras, ncas => sd_ncas, nwe => sd_nwe,
                ba => sd_ba, a => sd_a, dq_w => sd_dq_w, dq_r => sd_dq_r);
   end generate;

   ram_done <= ch1_ready or ch2_ready;   -- PSX.sv

   iddr3 : entity work.ddr3_model_small
   generic map (LAT => 15)
   port map (clk => clk2x, busy => ddr3_BUSY, burstcnt => ddr3_BURSTCNT, addr => ddr3_ADDR,
             dout => ddr3_DOUT, dout_ready => ddr3_DOUT_READY, rd => ddr3_RD, din => ddr3_DIN,
             be => ddr3_BE, we => ddr3_WE);

   process
   begin
      wait for 2 us;
      sdram_init <= '0';
      wait for 100 us;
      reset <= '0';
      report "reset released";
      wait for RUN_US * 1 us;
      report "run finished";
      done_sim <= true;
      wait;
   end process;

   -- program results: RAM writes to 0x100-0x11F, on the RAM interface clock
   sd_base <= f_clk when SPLIT = 1 else clk1x;
   process (sd_base)
      file fr : text open write_mode is "ram.log";
      variable l : line;
      variable a : integer;
   begin
      if rising_edge(sd_base) then
         if ram_ena = '1' and ram_rnw = '0' and ram_dma = '0' then
            a := to_integer(unsigned(ram_Adr(22 downto 0)));
            if a >= 16#100# and a < 16#120# then
               write(l, to_hstring(to_unsigned(a, 12)) & " " & to_hstring(ram_dataWrite) & " " & to_hstring(ram_be) &
                        " at " & integer'image(now / 1 ns) & " ns");
               writeline(fr, l);
               if a = 16#11C# then
                  report "done marker written at " & integer'image(now / 1 ns) & " ns";
               end if;
            end if;
         end if;
      end if;
   end process;

end architecture;
'''

SDRAMMAP = '''         SDRAM_EN => '1',
         SDRAM_DQ => sd_dq_w, SDRAM_DQ_IN => sd_dq_r, idx_o => open,
         SDRAM_A => sd_a, SDRAM_DQML => open, SDRAM_DQMH => open, SDRAM_BA => sd_ba,
         SDRAM_nCS => sd_ncs, SDRAM_nWE => sd_nwe, SDRAM_nRAS => sd_nras, SDRAM_nCAS => sd_ncas,
         SDRAM_CKE => open, SDRAM_CLK => open,
         refreshForce => ram_refresh, ram_idle => open,
         ch1_addr => "00" & ram_Adr, ch1_dout => open, ch1_dout32 => ch1_dout32, ch1_din => (others => '0'),
         ch1_req => ram_ena and ram_rnw, ch1_rnw => '1', ch1_dma => ram_dma, ch1_cntDMA => ram_cntDMA,
         ch1_cache => ram_cache, ch1_ready => ch1_ready,
         cache_wr => cache_wr, cache_data => cache_data, cache_addr => cache_addr,
         dma_wr => dma_wr, dma_reqprocessed => dma_reqprocessed, dma_data => dma_data,
         ch2_addr => "00" & ram_Adr, ch2_dout => open, ch2_din => ram_dataWrite,
         ch2_req => ram_ena and not ram_rnw, ch2_rnw => '0', ch2_be => ram_be, ch2_ready => ch2_ready,
         ch3_addr => (others => '0'), ch3_dout => open, ch3_din => (others => '0'), ch3_req => '0', ch3_rnw => '1',
         ch3_be => "0000", ch3_ready => open,
         dmafifo_adr => "0000" & dmafifo_adr, dmafifo_data => dmafifo_data, dmafifo_empty => dmafifo_empty,
         dmafifo_read => dmafifo_read'''


def const_for(name, typ):
    if name in CONST_ONE:
        return "'1'"
    if typ.startswith("joypad_t"):
        return "JOY0"
    if typ.startswith("integer"):
        return "0"
    if typ == "std_logic":
        return "'0'"
    return "(others => '0')"


def portmap(src, split):
    s = open(src).read()
    ent = s[s.index("entity psx_top is"):s.index("end entity;")]
    port = ent[ent.index("port"):]
    maps = []
    for m in re.finditer(r"^\s+(\w+)\s*:\s*(in|out|buffer|inout)\s+([^;:=]+?)(?:\s*:=\s*[^;]+)?;?\s*(--.*)?$",
                         port, re.M):
        name, d, typ = m.group(1), m.group(2), m.group(3).strip()
        if d == "in":
            v = TB_IN.get(name, const_for(name, typ))
            if split == 0:
                v = {"c_clk": "clk1x", "c_clk2": "clk2x", "c_clk3": "clk3x"}.get(v, v)
            else:
                v = {"c_clk": "f_clk", "c_clk2": "f_clk2", "c_clk3": "f_clk2"}.get(v, v)
        else:
            v = TB_OUT.get(name, "open")
        maps.append(f"         {name:<22} => {v}")
    return ",\n".join(maps)


def main(src, out):
    t = TEMPLATE.replace("@PORTMAP0@", portmap(src, 0)).replace("@PORTMAP1@", portmap(src, 1))
    t = t.replace("@SDRAMMAP@", SDRAMMAP)
    open(out, "w").write(t)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
